### ISSUE TITLE
Create and Maintain UXR instructions

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#12]
### Overview
We need UXR instructions for the people doing the interviews so that the experience is consistent across all the interviews

### Dependencies
Questionnaire form #11

### Action Items

- [x] UXR designer
   - [x] Create a document 
   - [x] Add the training questions to it
- [x] UXR role tester
  - [x] Send feedback on UXR instructions and any changes to be added to final instructions
  - [x] Thad to update google form to pre-populate email address of interviewee
- [x] UXR designer
   - [x] Update the training questions
- [x] UXR role tester
  - [ ] Send feedback on UXR instructions and any changes to be added to final instructions
- [x] UXR designer
  - [ ] Add Q&As as they come in

### Resources/Instructions
[UXR Instructions doc](https://docs.google.com/document/d/1cQumMP3mBUR595ZUkOgxoiLPkLL4WmgRWcAP_e3cWoQ/edit)
[Editable Interview form](https://docs.google.com/forms/d/1iiQZieGTDXMzwdiSdjIYhKQYjmc1YCMvfzVG08bswEI/edit?usp=sharing)

Instructions
**Name**
Know how to pronounce the name of the person you are interviewing before you start the interview if possible.
Use their name, instead of pronouns whenever possible.
If they mention someone else, please refrain from assuming the gender of the person they mentioned, and use they, them if you are unable to use their name.

**Geographic info**
Know their time zone

**Comment by MarianneAnthonette** [comment]
@naomiec Completed the first pass of UXR instructions feedback (made suggestions on the doc). Let me know if you want to talk more about the specific feedback / have other questions.

**Comment by MasSamH** [comment]
@thadk - Thad to update google form to pre-populate email address of person being interviewed.

**Comment by ExperimentsInHonesty** [comment]
I think is ready to review with one final UXR, by running through the training with them when we are ready.

**Comment by ExperimentsInHonesty** [comment]
The form needs one last revision @thadk, please update the clark kent form to be a copy of the current form draft.

**Comment by MasSamH** [comment]
@thadk can you un-populate all the entries on the Clark Kent form - except the ones on the first page. [we are trying to simulate the same experience that they will have, when they are doing the interview. Thanks

**Comment by thadk** [comment]
Fast fill link: https://docs.google.com/forms/d/e/1FAIpQLSdGrTnziCG6STVQPkdYxKbGblRhpzF1-GeyXZdlmh3Z14_6UA/viewform?usp=pp_url&entry.963965308=000&entry.666737716=Code+Island&entry.7436934=Clark+Kent&entry.2107947631=Clark+Kent&entry.1936764276=1&entry.1596745969=1&entry.20968895=1&entry.220171659=1&entry.744655585=1&entry.87105960=1&entry.764846038=1&entry.838021204=1&entry.2090362621=1&entry.1620052194=1&entry.1755843168=1&entry.1513441199=1&entry.115635811=1&entry.725190403=1&entry.830064905=1&entry.2133624628=1&entry.1392108993=1&entry.270807956=1&entry.1254273785=1&entry.1341981479=Batman&entry.367451046=Yes&entry.1777111311=Clark+Kent&entry.526388299=Save+Gotham&entry.26483174=Video&entry.1444254824=1&entry.1540797580=Batcave+visit&entry.1513478109=Email+Clark&entry.611037114=Yes&entry.1601355305=Clark+Kent&entry.1619466247=Rescue+someone&entry.567205019=Video&entry.1994972314=1&entry.1400149957=Batcar&entry.1230232240=Take+a+ride&entry.1582132702=No&entry.1550151393=Clark+Kent&entry.769408763=I'm+batman.&entry.1722247594=10&entry.763928116=One+millenium.&entry.1124824014=Yes&entry.1454706658=Never&entry.934901218=Clark+Kent&entry.1365932542=1&entry.737328644=10&entry.1421219581=Clark+Kent&entry.1809304853=No&entry.1693546739=My+co-captain+Robin&entry.2138785186=N/A&entry.1923194020=Fully+public

Only first page: https://docs.google.com/forms/d/e/1FAIpQLSdGrTnziCG6STVQPkdYxKbGblRhpzF1-GeyXZdlmh3Z14_6UA/viewform?usp=pp_url&entry.963965308=000&entry.666737716=Code+Island&entry.7436934=Clark+Kent

**Comment by ExperimentsInHonesty** [comment]
UXR instructions have been updated with the last two training session Q&As and links to the fun retros.
