### ISSUE TITLE
Create UXR workflow scripts for data organization

### ISSUE THREAD

**Issue by thadk** [codeforamerica/brigade-playbook#120]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/283343/107132502-9b5b1280-68ad-11eb-8f17-4b2543cd927b.png">

Thad to create 2 scripts: 
- [x] The first allows UXRs to transfer the cells they divide the particular transcription ideas into, over into the next sheet transposed;

- [x] Then the second script will take that **whole range of entries from the second sheet that they've finished and append them to all the other UXR's entries** e.g. on the Brigades Highest Priorities sheet.
  - It should check if it has already been done and refuse if so, until the would-be duplicates are removed. 
  - Maybe there can be an "already copied" column in the original sheet which it can maintain.
 

- [x]  From #17 **Streamline making well documented practices and processes public**: Write a script to automatically post any asset that has a rating of 5 "make resource public" to the public facing spreadsheet.  (Who runs this script when? We could just use =importrange() but security would be weak, at the very least will make a query() on the existing private one into another sheet of just public resources. If people need to publish the public facing one, they can just copy/paste it over) 
   - Finished: see [auto pop sheet](https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit?ts=5f416138#gid=972059661)
   - [Auto pop sheet v2](https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit#gid=186025086)

For the third here are the links 
- [BOP Processes and Practices Data](https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit?ts=5f416138#gid=0)
- [BOP Processes and Practices Data - INTERNAL](https://docs.google.com/spreadsheets/d/1ZyeIDeHnzwjnkfYuhzeUZQo5tYXpbdnF-HKqN8cZy_A/edit#gid=0)

**Comment by Baleja** [comment]
Update from Thad: 
All remaining interview transcription sheets will have OtterAI transciptions in them by later today
Second, UXR automation script ready by mid-late next week
For streamlining making documented practices and processes public - in progress 

@marianne - encourage UXR to focus on first steps on all of the transcriptions (e.g. parsing out the 'ideas'). 
Thad, will then run the scripts next weekend.

**Comment by Baleja** [comment]
@thadk to consider Row12-row51, Row 52 is extra topics have a safety cushion of around 15 ideas. Moved from issue #57

**Comment by Baleja** [comment]
Progress: Mari & Thad finalising coding issues

**Comment by Baleja** [comment]
Progress: Script is running clean, for spaces where there was a "0" or "blank". Mari and thad have been working together to fix the bugs. Please test on where the ranking was completely empty. 
@MarianneAnthonette to check the data organisation instructions so that the sheet are clean and can be read by the script.

**Comment by Baleja** [comment]
1. Make a copy of the superman form
2. Take the survey in the copy of the superman form 
3. Create the google sheet for the form
4. Add "0" to the rating scale
5. Take the survey again.
6. Look at the spreadsheet to see if the "0" generated a new column
@ExperimentsInHonesty

**Comment by thadk** [comment]
Reopening for bonnie to do previous comment, I'll hide the other parts.

**Comment by ExperimentsInHonesty** [comment]
Process:
- Make test form[edit form](https://docs.google.com/forms/d/1Vtg2Jj0syIyuPH5Y7YAz5TNWpJtu3zT8VHSE-r1u0tk/edit) (using superman form)
- Connect form to [test spreadsheet](https://docs.google.com/spreadsheets/d/19yYGIwXzwvSg9TpDplFI-EZdzozBAqr6ljFSoHJFWr8/edit#gid=1917925959)
- Filled out test form using [view form](https://docs.google.com/forms/d/e/1FAIpQLSeC1BeIxQ_WFyV_hMoNYxbw93aFSslb0BjE9k2YXA98LYpcUQ/viewform) and all 6's except for second question (1.0.1 Days of action (for example, the National Day of Civic Hacking this past September)) where I answered nothing and put 0 below into 1.0.1.1
- Changed the test form to include 0 on the formerly 1-6 rating
- Filled out test form again using 0 in the question # 1.0.1

Conclusion - The only thing changed was that the Zero shows up appropriately in the correct column.  So we can add zero to the current form.
![Screen Shot 2021-02-11 at 9 11 07 AM](https://user-images.githubusercontent.com/37763229/107671822-1d01c600-6c49-11eb-9d41-b7ddd87cad2d.png)
