### ISSUE TITLE
BOP Prioritization on Miro - Ceci

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#127]
### Overview
We need your help with a quick prioritization of features that define usability  (3-5 min)

### Details
We are working on an evaluation of the current BOP's usability and how useable other organizations playbooks are.  In order to complete this analysis we have to establish how we define usability.  We have identified 9 criteria.  Please help us sort them in order of importance.

### Action Items

- [ ]  @cfischerbenitez Using the instructions in the video below, use Miro to prioritize the cards.

### Resources/Instructions
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)
[How to sort the cards for prioritizing the final report video](https://www.awesomescreenshot.com/video/2663274?key=ca3d0687b3fa493528b0104afc7dfe68)

**Comment by MasSamH** [comment]
Slacked Ceci 02.01.21.

**Comment by Baleja** [comment]
Can @MasSamH make a video (on loom or awsome screenshot) about what cece needs to prioritise and how to do it on Miro.

**Comment by Baleja** [comment]
ETA: Thursday 14th Jan

**Comment by Baleja** [comment]
Dear @MasSamH I know that you are busy so I will tale up these action items for you.
 @Baleja 
- [ ] copy and paste the prompt from the Miro board to other peoples board
- [ ] Duplicate miro cards fo yourself 
- [ ] Record generalised (don't use names) video of how to sort the cards. - Explain prompt as much as possible and demonstrate sorting from most to least. <1 minute video

**Comment by Baleja** [comment]
https://www.awesomescreenshot.com/video/2382803?key=40b5e208cc3a6dd5165ee98b06c61ef1

**Comment by MasSamH** [comment]
@Baleja Was just about to get going on this earlier, thankfully saw your comment before starting out. I thought the instructional video was very clear and the screen capture kit a great find. 

One suggestion is to frame earlier in the voiceover the purpose of what we are asking them to do - prioritization of the usability features. So we turn the dial up on the outcome of what we want from them, then shift to the mechanics of using Miro. 

Something along the lines of:
'We asked for your help to prioritize usability features for a future BOP playbook resource. By completing this prioritization exercise - what you consider important, and what you consider less important - you will be informing our understanding of what matters most to you and other Brigade leads in a playbook resource. 
This short instructional video guides you through this prioritization exercise using the Miro Board collaboration tool.’

----------------------------
Also, wonder whether, with the other boards (under the internal team members) displaying a different set of cards, we should either add a divide line on the Miro board in case they scroll up and wonder why these are different. Or we lock those other cards in Miro. Or, add a point to the voiceover that there are 'other boards on Miro that have been used by other team members, but they only need to focus on the 'usability cards' for the purpose of this exercise. I could be over-thinking this.

**Comment by Baleja** [comment]
@Baleja Delete pink and blue boards and re-make description video with intent.

**Comment by raquelnish** [comment]
@Baleja  check out the  Source for these topics description, [BOP Comparative Analysis sheet](https://docs.google.com/spreadsheets/d/1IVK9Z6xrO7vbKx_fJAvWt-cK1agnuTQreEAU_R7PNVg/edit#gid=2026965152)

tab> card sorting because in the beginning there was a big description which you could use/edit since it makes it easier for people to understand what the feature is about.

**Comment by Baleja** [comment]
GETTING THERE not quite yet https://www.awesomescreenshot.com/video/2576529

**Comment by Baleja** [comment]
The Miro cards were updated with more topic description from BOP comparative analysis

**Comment by cfischerbenitez** [comment]
Done!
