### ISSUE TITLE
Create Miro board for initial additional topics affinity mapping 

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#129]
### Overview
We need to set up a Miro board to address the additional BOP topics/suggestions from the interviews.

### Action Items
- [x] Set up Miro board space for the focus area: Ideas for future BOP topics
- [x] Filter sheet, and copy & paste responses, questions, and identifying numbers into cards.
- [x] Tag the cards with the appropriate segments.

### Resources/Instructions
[Highest Priorities - Additional topics](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=0)
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)

**Comment by MarianneAnthonette** [comment]
1/31: Miro board has been set up with ready responses. The next update to the board will be before the Wednesday initial affinity mapping session.

**Comment by MarianneAnthonette** [comment]
### How to add data from an interview to the Ideas for future BOP topics Miro board

#### Before you get started
Make sure that the interview responses are properly labeled in column D of the [Additional topics](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=0) sheet. 

#### Instructions 
1. Open the Miro board and navigate to the [Ideas for future BOP topics Miro Board](https://miro.com/app/board/o9J_kgJShaA=/).
2. Open the [Additional topics](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=0) sheet. **Stay on this sheet.**
4. Find the interview responses you want to add to the Miro board by locating the interview ID in column A.
5. Select and copy all the text cells in column D (Labels/Tags) that belong to the interview.
6. Go back to the Miro board and click on the Ideas for future BOP topics Miro Board.
7. Paste the text onto the board. It should create post-its.
   -  If you are only pasting text from one cell, you need to create a post-it manually and paste the text onto it.
8. Stay selected or reselect the post-its you've created (hold SHIFT and click on the post-its).
9. Select the **add tag** icon and apply the correct tags. Refer to the Additional topics sheet columns to know which tags to use specific to the interview:
   - **Size** (column E): Tags available - XSMALL, SMALL, MEDIUM, LARGE, XLARGE
   - **Interview** # (column F)
10. Go back to the Additional topics sheet and type in **Yes** in column G (Moved into Miro board?) for all the labels/tags you've created post-its of.

**Comment by MarianneAnthonette** [comment]
1st affinity mapping session done 2/3. Top 3 groups (in order): Volunteer recruitment and engagement, project management, collaborating and connecting within the network

![Screen Shot 2021-02-04 at 8 12 31 AM](https://user-images.githubusercontent.com/20882817/106921477-e7952f80-66c0-11eb-9de1-0fd61e2256f8.png)
![Screen Shot 2021-02-04 at 8 14 22 AM](https://user-images.githubusercontent.com/20882817/106921669-14e1dd80-66c1-11eb-817a-79d760b19433.png)
![Screen Shot 2021-02-04 at 8 14 41 AM](https://user-images.githubusercontent.com/20882817/106921695-190dfb00-66c1-11eb-8b69-d49d4492f509.png)

**Comment by MarianneAnthonette** [comment]
[Creating Interview Data Post-its on Miro](https://docs.google.com/document/d/1ilLivl8yzdieWcJakFrKLEFRbcnh8IhFRLX6WZJld3M/edit#heading=h.8dt2qeurfmti)

Instructions have been moved to an internal document as a resource for researchers.
