### ISSUE TITLE
Add Playbook examples 

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#13]
### Overview
Identify playbook examples from other organisation in the Civic Tech space, to potentially assist in BOP at later delivery phase

### Action Items

- Add all research to competitor analysis template
   - Identify examples 
   - Identify common and unique features 

### Resources/Instructions
[Competitor Analysis Template](https://docs.google.com/spreadsheets/d/1IVK9Z6xrO7vbKx_fJAvWt-cK1agnuTQreEAU_R7PNVg/edit)
[US Digital Services Playbook](https://playbook.cio.gov/)

**Comment by MasSamH** [comment]
@raquelnish investing other examples in Civic Tech space

**Comment by ExperimentsInHonesty** [comment]
@raquelnish Here is the org that is helping people find remote jobs in ireland: https://growremote.ie/. If they don't have a playbook on their site , let me know and ill connect you with Rose (one of the leads of the org)

**Comment by MasSamH** [comment]
Raquel gave an overview of competitive analysis of playbook examples. Reviewing type of content, format. 
Thad shared Method cards. Good example of accessible, guided content. [Method Cards](https://methods.18f.gov/decide/comparative-analysis/)
@raquelnish Raquel is continuing to work on the comparison. Adding structure to comparison - content and presentation (form)

**Comment by MasSamH** [comment]
- [ ] Regarding comments people are making about 'connecting with other people' we should retain this information but consider it outside of current scope and possible areas for additional research / interviews in the future. 
@ExperimentsInHonesty and @thadk to connect separately.

**Comment by MasSamH** [comment]
@raquelnish 
- [ ] Adding extra tab to cover images in the BOP Competitive Analysis Template
- [ ] Examples can go into the Research report

**Comment by MasSamH** [comment]
For the Research report, Raquel will combine insights from interviews with the competitive analysis.

**Comment by MasSamH** [comment]
@raquelnish Summarizing the findings into a PPT report 
Start with an outline on comparative analysis findings

Another example from Thad. 
[US Digital](https://policies.usdigitalresponse.org/inclusion-guidelines)
Also uses gitbook that Jonathan mentioned

**Comment by MasSamH** [comment]
Miro Board populated and prioritization started by Project Team members against Usability card. 
@ExperimentsInHonesty on the Tuesday week call, can you help us determine the prioritization that you want to see. 
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)

**Comment by MasSamH** [comment]
Raquel has created a new tab 'Report Option' that presents an easier visual representation of the content - gap analysis of BOP Playbook versus other Playbook example. See [BOP Comparison Analysis Template](https://docs.google.com/spreadsheets/d/1IVK9Z6xrO7vbKx_fJAvWt-cK1agnuTQreEAU_R7PNVg/edit?pli=1#gid=286636582)
The usability characteristics will also be assessed against the other playbooks. 
@ExperimentsInHonesty do you want to take a review of the how this analysis is done and let Raquel know. @raquelnish @MarianneAnthonette

**Comment by MasSamH** [comment]
Miro Board populated and prioritization started by Project Team members against Usability card. 
@ExperimentsInHonesty on the Tuesday week call, can you help us determine the prioritization that you want to see. 
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)

**Comment by MarianneAnthonette** [comment]
Purpose of criteria sorting activity:
- To determine the structure for Raquel's comparative analysis report
- We can do a deeper analysis and take the highest needs/priorities identified and do an analysis of the BOP measured against the criteria

@MasSamH Create/duplicate card sort boards for Brigade lead sample (2 small, 2 medium)

After new inputs, tally the votes.

**Comment by MasSamH** [comment]
Added blank boards for populating by Brigade lead x 5 (includes one spare), thanks Sam
[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/l)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty will outreach to Janet and Tyrek once we have established the motivations for including the 'Card content' and 'Suggestions from interview script'. 
@raquelnish can you help here to explain why we included on the Miro these other cards? 
Thanks Sam

**Comment by raquelnish** [comment]
@MasSamH @thadk @ExperimentsInHonesty  The blue and pink boards have all the content from the comparison analysis,  they are there just for the future when we might need to prioritize the playbook content according to interviews feedback. But for the brigade people that will sort cards for usability features, those boards can be deleted. They only need to see the green one.

**Comment by MasSamH** [comment]
@MasSamH to delete the blue and pink boards on Miro (just for the new people).

**Comment by MasSamH** [comment]
- [ ] When do we want to schedule for the Miro board session

**Comment by MasSamH** [comment]
Surplus boards deleted, thanks Sam

**Comment by Baleja** [comment]
Bonnie sent this message to Janet, Tyrek & Thad via slack
Hi Tyrek and Janet, we are hoping you can help us with some prioritization using miro . We would be happy to walk you through it if you like.  On this board, please find the section with your name and prioritize the cards on the pinkish board (under your name). If you do want a walk through, the team meets on Tuesday and Thursdays at 11 CST /12 EST and on Saturday’s at 1pm CST/ 2pm EST

**Comment by celeste-hub** [comment]
@celeste-hub to update the miro board with searchability.

**Comment by celeste-hub** [comment]
Added the searchability to the miro board.
