### ISSUE TITLE
Add the length of the interviews from Otter.ai 

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#141]
### Overview
We want to add the interview time from otter.ai to the individual issues for the unassigned interviews.

### Action Items

- [ ] Conviene with @MarianneAnthonette about where to add the times in the sheet and then add to corresponding issues in UXR

**Comment by MarianneAnthonette** [comment]
@Baleja I've gone ahead and added the length of interview to each interview that has a transcription sheet (I used the Otter.ai time format which is hours:minutes:seconds). You can view it on the interview tracking sheet (column S).

@raquelnish I think you need to update an instruction doc to add the step to fill-in the interview length when you are creating the transcription sheet (Issue related to creating our internal research coordination instructions: #122)

**Comment by raquelnish** [comment]
I have updated the Instructions on 'BOP Documentation 1' including the step of adding the interview length.

**Comment by Baleja** [comment]
I have added the interview lengths on all incomplete interview issues under Overview.
