### ISSUE TITLE
Quantitative analysis: intro text and summary statistics

### ISSUE THREAD

**Issue by jkropko** [codeforamerica/brigade-playbook#144]
### Overview
For the report that we will be collectively writing with the quantitative analysis findings, we need good writing to explain what we are doing, where the data come from and what the data mean. We also need as a first analysis a simple but descriptive report of the summary statistics in the data -- means, ranges, counts, etc. of the rankings in particular.

### Dependencies
Get up to speed with R Studio, R Markdown, etc (which we've done!)
The quality of the analysis goes up with more of the data cleaned and placed into the final Google sheet we pull from.

### Action Items

- [x] Write introduction, continue to rewrite as we develop the project
- [x] Figure out summary stats and a neat way to present them

### Resources/Instructions
[Slides on tidying data in R](https://cfa.slack.com/files/UL9U380TH/F01HVD67SMU/tidydata.pdf?origin_team=T024F66L9&origin_channel=C019RCM15FE)
[Using ggplot in R](https://cfa.slack.com/files/UL9U380TH/F01J6BDA04Q/knitr_reference.pdf?origin_team=T024F66L9&origin_channel=C019RCM15FE)

**Comment by raquelnish** [comment]
We have finished the summary stats on January 26th
I have written an introduction but I believe it will change because it has to include the questions we wanted to answer with this research and we are still working with the data to see what we get from it.
