### ISSUE TITLE
Create OKRs

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#15]
### Overview
Establish a consensus on Project OKRs, propose a framework for meeting these objectives, and how we will measure and report.

### Action Items

- [x] Research OKRs for Civic Opportunity Project, and discuss options with Bonnie, Naomi, and Thad
- [x] Establish Project Objectives
- [x] Establish Key Results deliverables for each Objective
- [x] Review proposal with team
- [x] Send OKRs to Will for approval 
- [x] Create new issues against each of the WBS items https://github.com/codeforamerica/brigade-playbook/issues/37
- [x] Make changes/revisions to OKRs
- [x] Finalize OKRs

### Resources/Instructions
[What are OKRs?](https://www.bernardmarr.com/default.asp?contentID=1456)
[Civic Opportunity Project OKRs](https://docs.google.com/document/d/108pM9t4dtTs2NO9quUT-vr0DFF-59_-qcT61yuE_x_I/edit#)
[BOP Project WBS & OKRs New](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU)
[OKRs BOP Working document Old](https://docs.google.com/document/d/1C8wakjw7ZgsZWrijIcO5H34rUK5KZOmkl21WWFvGCis/edit#l)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty @thadk Just looking at defining some OKRs for issue [#15](https://github.com/codeforamerica/brigade-playbook/issues/15). Have pulled together some ideas (certainly not anything more than that at this stage). 

[OKRs BOP Working document](https://docs.google.com/document/d/1C8wakjw7ZgsZWrijIcO5H34rUK5KZOmkl21WWFvGCis/edit#l)

Bonnie, Thad, if you are free one hour before our call tomorrow, we could meet to build this out further? I'll send over an invite. No worries if you can't make it. 

Looking forward to the catch up. 

Sam

**Comment by MasSamH** [comment]
@ExperimentsInHonesty
Hi Bonnie, @ExperimentsInHonesty 

For homework, if you provide guidance on the 'objective', I'll go in and add thoughts on 'key results'. 
I could also put the Work Breakdown Schedule into the project style guide? 
Plus do the flip of paragraphs to give us the One Sheet for this project, so folk are clear this is one project as part of the Civic Tech Structure programme of work?

Anything else you want me to take a look at? Or reading that I should get on with? 

Thanks
Sam

**Comment by ExperimentsInHonesty** [comment]
reformat okrs into a spreadsheet.  Keeping the google doc and putting a link to the spreadsheet into the doc.
