### ISSUE TITLE
Quantitative Analysis: Visualization

### ISSUE THREAD

**Issue by jkropko** [codeforamerica/brigade-playbook#150]
- [x] Add background shading to the individual boxes in the correlation plot
- [x] Make a google doc with the clusters, share with group to name the clusters

**Comment by reemux** [comment]
Google sheet with clusters created and shared with team. Can find it under Research Analysis google Drive.

**Comment by reemux** [comment]
Working on debugging my R code. New correlation plot should be ready as soon as that is successfully done.

**Comment by reemux** [comment]
Clusters done.
Background shading added to correlation matrix.
