### ISSUE TITLE
Quantitative Analysis: Graded Response Model

### ISSUE THREAD

**Issue by jkropko** [codeforamerica/brigade-playbook#151]
- [x] Get the BOP data into the right format for GRM
- [x] Get the GRM code working on the BOP data
- [ ] Write up descriptions of the extremity and discrimination coefficients, the item characteristic curves (with plot()) and the factor scores
- [ ] Find way to merge the factor scores with the brigade IDs (and possibly MSA)
- [ ] Share a .csv file with @reemux and @tan-zhou so our latent variable (brigade preparedness) can be integrated into their analyses

**Comment by osnickersnee** [comment]
Progress:  BOP data was transformed from long to wide format, GRM code now works.
Blockers:  Experienced numerous errors with R code, but @jkropko proposed and implemented effective solutions to finish the analysis. Thank you, Jon!
Availability : Available this week but will decrease when I start full-time job.
Estimated date of completion: 2/5/2021 if all goes well.

**Comment by jkropko** [comment]
Completed GRM and added the "preparedness scores" to the "preparedness" tab of the Brigade's Highest Priorities sheet: https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit?usp=sharing
