### ISSUE TITLE
Create a frequency table to organize code usage

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#152]
### Overview
We need to set-up an automated frequency table in the codebook that tallies up the codes to organize and aid qualitative research activities.

### Action Items
Create a frequency table in the codebook that calculates the following (by priority):
- [x] For each question, what are the top codes being used?
- [x] Across brigades, how frequently is each code being used? What are the top codes being used?
- [x] For each brigade, what are the top codes?

### Resources/Instructions
[Code Book](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=143235866)

**Comment by thadk** [comment]
Made a first pass at the middle item: <img width="482" alt="image" src="https://user-images.githubusercontent.com/283343/106097016-96a39b00-6104-11eb-85f3-d3564ebcb5e8.png">

We should be able to reuse the approaches for the other two. Can you create sheet(s) with the =UNIQUE(questions) and =UNIQUE(brigades) formatted roughly how you'd like the code use described? I couldn't think of a great way to do it totally dynamically except a pivot table and I think that'd require condensing the codes down to a single column somehow. 

These fancier ones might be better done in R.

**Comment by Baleja** [comment]
Action Items @thadk :
 2 news sheets 
1.Rows are questions, the columns are codes, values are counts
2.Rows are brigades, columns are codes and values are counts
