### ISSUE TITLE
Create Miro board for initial affinity mapping of CfA-related responses

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#153]
### Overview
We need to set up a Miro board with tagged responses related to CfA to prepare for the initial affinity mapping session.

### Action Items
- [x] Set up Miro board space for the focus area: Relationship with CfA
- [x] Filter sheet, and copy & paste responses, questions, and identifying numbers into cards.
- [x] Tag the cards with the appropriate segments.

### Resources/Instructions
[Highest Priorities - Ranking](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=825325863)

[Code Query](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=514763108)

[Miro Board](https://miro.com/app/board/o9J_kgJShaA=/)

**Comment by MarianneAnthonette** [comment]
1/31: Miro board has been set up.
Blocker: Codes need to be corrected so that only CfA-related responses populate the board.
The next update to the board will be before the Wednesday initial affinity mapping session.

**Comment by MarianneAnthonette** [comment]
### How to add data from an interview to the Feedback to / Relationship with CfA Miro Board

#### Before you get started
Make sure that the interview responses are correctly coded with a CfA code (ensure that the CfA code is used properly and makes sense for the quote).

#### Instructions 
1. Open the Miro board and navigate to the [Feedback to / Relationship with CfA Miro Board](https://miro.com/app/board/o9J_kgJShaA=/).
2. Open the [Code Query](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=514763108) sheet. **Stay on this sheet.**
3. In cell B1, type **CfA%** and hit enter. Now the responses from the ranking sheet that have been assigned a CfA code will appear on the sheet.
4. Find the interview responses you want to add to the Miro board by locating the interview ID in column A.
5. Select and copy all the text cells in column C (Response) that belong to the interview.
6. Go back to the Miro board and click on the Feedback to / Relationship with CfA Miro Board.
7. Paste the text onto the board. It should create post-its.
   -  If you are only pasting text from one cell, you need to create a sticky note and paste the text onto it.
8. Stay selected or reselect the post-its you've created (hold SHIFT and click on the post-its).
9. Select the **add tag** icon and apply the correct tags. Refer to the Code Query sheet columns to know which tags to use specific to the interview:
   - **Size** (column D): Tags available - XSMALL, SMALL, MEDIUM, LARGE, XLARGE
   - **Interview** # (column E)
10. Unselect all the post-its.
11. One-by-one, click on each post-it and select the **add tag** icon and apply the correct **Questions** tag. Refer to the Code Query sheet column B to know which tag to use specific to the interview.

**Comment by Baleja** [comment]
This is instructions for new UXRs to analyse interviews, it should be living as a deck with some short videos, screenshots and gifs. 
Then we will link this in a wiki.

**Comment by MarianneAnthonette** [comment]
Initial affinity mapping moved to next week. Need to review codes.

**Comment by Baleja** [comment]
We are aiming to have 3 more UXRs to complete the transcription verification training to help complete the interview transcription. 
Coding will need to be done within a group to make sense of the ever adapting language. 
As soon as bonnie OKs self training we should start recruiting.

**Comment by MarianneAnthonette** [comment]
[Creating Interview Data Post-its on Miro](https://docs.google.com/document/d/1ilLivl8yzdieWcJakFrKLEFRbcnh8IhFRLX6WZJld3M/edit#heading=h.8dt2qeurfmti)

Instructions have been moved to an internal document as a resource for researchers.
