### ISSUE TITLE
Adding brigade sizes according to the MSA

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#157]
### Overview
We need to be able to tag the brigades with size according to NAC election jurisdiction (region & 1/3 or 2/3 MSA size) 

### Action Items
- [x] Provide spreadsheet to analysis team
- [x] Create new tags

**Comment by Baleja** [comment]
Thad will send the sizing data to Tan #146

**Comment by thadk** [comment]
I just copied and pasted from Will's spreadsheet and my MSA spreadsheet and sent to Tan. I didn't do any special work around the 1/3 or 2/3, just left the "L" and "S" from Will's spreadsheet as of today.
