### ISSUE TITLE
Discuss the next steps for regressions and visualizations 

### ISSUE THREAD

**Issue by tan-zhou** [codeforamerica/brigade-playbook#161]
### Overview
We need to discuss what kind of analysis we could do with the data set and how to best visualize the result. 

### Dependencies
Need GRM results about preparedness.  

### Action Items
- [x] Meeting with Reem to 
  - [x] Review current visualization 
  - [x] Discuss potential analysis/correlations we should explore

**Comment by tan-zhou** [comment]
Wasn't not able to meet on 2/6. Need to reschedule the meeting.

**Comment by tan-zhou** [comment]
Analyze factors by using the linear regression model, starting with one way.

**Comment by tan-zhou** [comment]
We meet on 2/20 and agreed that we will start with visualizing the general ranking of topics. 
@reemux will 
- plot the overall average ranking of topics among all the brigade
- plot the top 5 most highly ranked topics among 
  - small vs big size brigades 
  - long vs short term leaderships 
  - locations (pacific, east, south)
  - less prepared vs more prepared brigades (after getting the preparedness value from Jon)

@tan-zhou will explore the relationship between the responses we have and what we know about the brigades by examing 
- scatter plot
- regression line
between brigade preparedness and brigade size, length, locations, and MSA data. 

Our goal here is to produce baseline visualizations for future iteration and show preliminary results that may inspire our qual research.

**Comment by tan-zhou** [comment]
We'll meet with Jon this Saturday to work together on ggplot.

**Comment by reemux** [comment]
@reemux has done the following:
- [ ] plot the overall average ranking of topics among all the brigades

- [ ] plot the average ranking of topics by:
size
length of leadership
region
preparedness
