### ISSUE TITLE
Test out conditional formatting to block out rows on the transcription sheet

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#166]
### Overview
We need to test out if blocking out rows based on the response cell B53 and B118 on the transcription sheet is feasible so that the transcription sheet instructions + training can be simplified.

### Action Items
- [x] Create a formula to test blocking out rows with black based on cell B53
- [x] Create a formula to test blocking out rows with black based on cell B118

### Resources/Instructions
[Training Transcription Sheet](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923)

**Comment by MarianneAnthonette** [comment]
### For blocking out rows based on cell B53
- Apply to range: A55:E113
- Format rules: Custom formula is -> **=$B$53="No"**

![Screen Shot 2021-02-09 at 7 23 39 PM](https://user-images.githubusercontent.com/20882817/107460339-cbecb780-6b0c-11eb-9d80-41c4074d48e4.png)

### For blocking out rows based on cell B118
- Apply to range: A119:E120
- Format rules: Custom formula is -> **=$B$118="Never"**

![Screen Shot 2021-02-09 at 7 23 50 PM](https://user-images.githubusercontent.com/20882817/107460341-cdb67b00-6b0c-11eb-92a9-91169238031c.png)

**Comment by Baleja** [comment]
@raquelnish Would you be able to add this information to your instruction sheet? [Create & Update 1](https://docs.google.com/document/d/1ZSo1-XfC6gpXT6snyw7UcEororeaZN-lj4UfptcsJ8k/edit#)

**Comment by raquelnish** [comment]
This step was added to the [Create &Update 1](https://docs.google.com/document/d/1ZSo1-XfC6gpXT6snyw7UcEororeaZN-lj4UfptcsJ8k/edit#heading=h.umhaeuaepkun)

**Comment by Baleja** [comment]
we have decided to use strikethrough.
