### ISSUE TITLE
Change Transcription Template columns names

### ISSUE THREAD

**Issue by raquelnish** [codeforamerica/brigade-playbook#167]
### Overview
The names of columns A-D  at the Transcription sheet template must make more sense, so new UXRs can understand them better

### Action Items
- [x] On the Transcription Template
   - [x] Change Column A
      - from: Field from Form
      - to: Questions from Form
  - [x] Change Column B
      - from: Existing text (form submission)
      - to: Ranking Response & Interviewer Notes
   - [x] Change column C 
      - from: exactly what OtterAI says (taken from audio)
      - to: Interviewee text before your edits (produced by OtterAI)
   - [x] Change column D 
      - from: Actual cleaned input
      - to: Interviewee text after your edits
- [x] run it on Transcriptions Sheets already created:
- [x] Move Row down to between row 10 and 11.  Making it the new 10, because 2-10 will move up.  See screenshots below

### Resources:
[Transcription Sheet template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)

**Currently the template look like this**
![Screen Shot 2021-02-11 at 10 44 11 AM](https://user-images.githubusercontent.com/37763229/107683210-280f2300-6c56-11eb-88d4-fd07878d5077.png)

**and we want it to look like this**
![Screen Shot 2021-02-11 at 10 46 29 AM](https://user-images.githubusercontent.com/37763229/107683458-6dcbeb80-6c56-11eb-8f3b-8284e5eb4013.png)

Script: https://colab.research.google.com/drive/10E_UA0feefZrph7OSi_ODVv8d3Zz6ft6

**Comment by Baleja** [comment]
Here is the link to the Wonder Woman https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923

**Comment by MarianneAnthonette** [comment]
Transcription column names have been changed for existing transcription sheets and the template. Updates to the formatting of older transcription sheets are being tracked in issue #199
