### ISSUE TITLE
Update question vs. code frequency table to not overcount codes

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#169]
### Overview
We need to update the question vs code frequency table so that it gives a more accurate representation of the codes for the qual analysis team to define more concrete research activities.

### Action Items
- [x] Update the formula so that for a brigade interview, for each question (1.0.0. to 1.0.19), a code must only be counted once. For example, if the response for one question was broken into 2 different cells, and both get coded success, only one of the success codes will be counted.

### Resources/Instructions
[Questions vs codes table](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=887494364)

**Comment by thadk** [comment]
Updated this "questions-vs-codes-perInterview" sheet: https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=887494364 

"This sheet ignores when multiple responses in the same question have the same code"
