### ISSUE TITLE
Initial write up from the frequency table

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#171]
### Overview
We need a way to communicate findings in the frequency table. We need to understand the state of the codes to give us more direction in the research analysis and deliverables.

### Dependencies
Issue #169 

### Action Items
- [x] Find the cells that have over 4 and above.
- [x] Create a document for talking points that arise from certain questions
- [x] Identify appropriate analyses (next steps)

### Resources/Instructions
[BHP- Questions vs code tab](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=887494364)

**Comment by MarianneAnthonette** [comment]
[Initial Write-up (before frequency table has been updated)](https://docs.google.com/document/d/1Ot51aWAvArjJYr8mJsiVjEJQcItFpxpighWJjNZqzVs/edit#)

**Next steps**
- Need to audit the codes + continue coding/tagging. This should be prioritized.
- Weed out overcounted codes on the frequency table.
- Align what’s coming out of the quantitative analysis with the preliminary qual findings from the ranking sheet. Which are the top topics (topics in order of high need to low need)? We need to bring in the quant now to begin scoping down the analysis.
- Update research analysis plan to create plans for each research question.
