### ISSUE TITLE
Create messaging doc for UXR recruitment

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#175]
### Overview
This will be messaging we use to recruit new UXR volunteers. 

### Action Items
- [x] Write messaging for recruitment 
- [ ] Adjust to various platforms

### Resources/Instructions
[Messaging for New Recruits](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit)

**Comment by Baleja** [comment]
From issue #74

**Comment by MarianneAnthonette** [comment]
Progress: Updated [messaging](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit) language for transcriber recruitment.

Q: Should we have messaging for recruiting for each different 'role' or create a generalized recruitment blurb?

**Comment by xtrementhusiast** [comment]
> Progress: Updated [messaging](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit) language for transcriber recruitment.
> 
> Q: Should we have messaging for recruiting for each different 'role' or create a generalized recruitment blurb?

A: I think we can have 1 blurb but we should list each role we're seeking to fill along with bullet points describing duties, expected time commitment, and any meetings they have to attend. This gives volunteers the chance to make a more informed decision.

**Comment by MarianneAnthonette** [comment]
> > Progress: Updated [messaging](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit) language for transcriber recruitment.
> 
> > 
> 
> > Q: Should we have messaging for recruiting for each different 'role' or create a generalized recruitment blurb?
> 
> 
> 
> A: I think we can have 1 blurb but we should list each role we're seeking to fill along with bullet points describing duties, expected time commitment, and any meetings they have to attend. This gives volunteers the chance to make a more informed decision.

Agree with including that information but it might be too much to include in a short outreach blurb. Probably best to create a role explainer document we can link to.

**Comment by MarianneAnthonette** [comment]
Role explainer + generalized recruitment messaging will be completed to later than **3/2**

**Comment by MarianneAnthonette** [comment]
**Progress**: Added generalized recruitment messaging to the [recruitment messaging doc](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit#). Created the [role explainer template](https://docs.google.com/document/d/1YAT_s_ZMBT3-3x8o1jZxjJiAJOVLw2WWKl1koTETAI8/edit#) but haven't added information in yet.
**Blocker**: There was a previous blocker - had to wait for my interview to be scheduled so I was unable to work on this issue.
**Availability**: I'll be _especially_ busy next week with limited availability (interview next Friday 3/12). Will probably only be able to do research coordination tasks and the meetings.
**Estimated date of completion**: First draft of the role explainer by Thursday 3/4.

**Comment by ExperimentsInHonesty** [comment]
Brought over from another issue
Created an initial draft of [messaging for Transcriber Recruitment](https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit). Did not include CTA and need help thinking of what this volunteer opportunity benefits (for the volunteer's end).

**Comment by ExperimentsInHonesty** [comment]
@xtrementhusiast  and @MarianneAnthonette 

I do think one overview of all the UX roles would be good and I don't have a problem linking to it from the wiki.  We just want the initial messaging to be specific to the role we are training for at the time.  At the point when all of our training has been written, then we can do a more general recruitment and will need language for that.

I just finished reading all the text above. I see David has customized each of the recruitment messages in the [BOP Messaging for Volunteer Recruitment ] (https://docs.google.com/document/d/1EdCZzFz3BT5WNUZOWQ5aHXYds7TaaaPWDCvqfGswnUU/edit#) document.  And has captured the value proposition for the volunteer on each one.  Looks good to me.

- [ ] We will still need what happens and what messaging we have to use for each.  _For instance, I think we can use a similar version of the text in a zoom registration link.  But we will want to have another message when they receive their confirmation of the training.  Perhaps sending them the link to the deck or whatever David feels would be helpful for them to receive in advance._

- [ ] We also need text for each of the stages

- [ ] @Baleja has been doing a lot of work to get everyone onboarded to slack, etc. (usually the coordinators job), perhaps there is language from that process that should also be in the document above.

**Comment by xtrementhusiast** [comment]
If needed, [here](https://docs.google.com/document/d/1dHcVqqfV_MRD_dMj6jAocxvwJYBqKZdVpdKV4_7gfe8/edit#) is updated messaging for Interview Transcription Verification training
