### ISSUE TITLE
Make Onboarding materials for understanding our project from a UX volunteer perspective

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#178]
### Overview
How to get the new people interested in Qualitative analysis. 

### Action Items
Set CLEAR objectives

**Comment by Baleja** [comment]
ITINTERARY: 
What we are doing:
Why its important:
How we do it:
What you will learn:

**Comment by ExperimentsInHonesty** [comment]
This will make a great slide
