### ISSUE TITLE
Fix formatting for "good first issue" for New trainees

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#184]
### Overview
The Issues on the UXR board link to the old transcription template. We need to reformat the already created transcription sheets to look as closely as "The Wonder Woman" Sheet as possible.

### Action Items
- [x] Reformat issues:
    - [x] #135 
    - [x] #162 
    - [x] #133 
    - [x] #142 
    - [x] #111 
 
- _Update Instructions to new format wherever possible_

### Resources/Instructions
[Old sheet](https://docs.google.com/spreadsheets/d/1ZkRRg6KB9jDo6z0ndSGz_riM1BFeItv0QvQ8I45yEs0/edit#gid=1088936555)
[New Format](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923)

**Comment by Baleja** [comment]
@Baleja Copy and paste formatting & conditional formatting  - [ ] 
@thadk Fixing rows 1,10 & 126 - [ ] 
@MarianneAnthonette Audit - [ ]

**Comment by thadk** [comment]
@Baleja please check this sheet and see if it is right (no data loss) and I'll run it on the others:
https://docs.google.com/spreadsheets/d/1WbtA-lUOW7OgOnrY9CBhbjlY8ZMchQK1ZFtlZhGfbZM/edit?skip_itp2_check=true#gid=1605694670
