### ISSUE TITLE
Create outreach message to Puerto rico

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#194]
### Overview
We want to get people excited about being interviewed, PR is new to the NAC. We need to reach out to him to get involved with our BOP project. 

### Action Items
- [ ] Create messaging 
- [ ] Reach out to Froi

### Resources/Instructions
[Contact List](https://docs.google.com/spreadsheets/d/12uNxqK9ZCrXuZzRJF1NSZVqkiSEcqU4YTC8WxHVHI8Q/edit#gid=14175688380)

**Comment by ExperimentsInHonesty** [comment]
He has joined us.  This is no longer necessary.
