### ISSUE TITLE
Analysis: BOP Awareness and Usage

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#198]
### Overview
We need to discover % of BOP awareness Brigade leads’ general sentiments and knowledge of the Brigade Organizer's Playbook.

### Research Questions
- What are Brigade leads’ general sentiments and knowledge of the BOP?
   - How might we create a high-value resource that addresses these sentiments and findings from the comparative analysis and usability criteria prioritization?
   - What format should the next playbook be in (it's currently a Google doc)?
   - What features are important for the next playbook to have?

### Action Items
- [x] Create initial analysis write-up of general sentiments and knowledge of the BOP (using the datasheet + affinity map)
- [x] Add onto initial analysis write-up by tying in comparative analysis and usability criteria prioritization (addressing the sub-questions)
   - **Dependency:** #70 
- [x] Complete analysis (once all data comes in) and create report content **(link to be added later)**

### Resources
[Miro board (affinity map + usability criteria prioritization)](https://miro.com/app/board/o9J_kgJShaA=/)
[BOP Awareness and Usage Data Sheet](https://docs.google.com/spreadsheets/d/1T3DVMbGVjlap_QnVx98vcRF650cD49JMPRFSj48yNuI/edit#gid=587189806)
[BOP Comparative Analysis (of current BOP and other civic tech playbooks)](https://docs.google.com/spreadsheets/u/1/d/1IVK9Z6xrO7vbKx_fJAvWt-cK1agnuTQreEAU_R7PNVg/edit#gid=2026965152)
[Brigade Organizer's Playbook](https://docs.google.com/document/d/1G_v53fGyHqdZNmXkDxqhqkzT7q2TBZ9Xmh9JkWtFQ8Y/edit#heading=h.v3vvoe3g4dep) 

### Deliverables
[BOP Comparative Analysis Report (incomplete)](https://docs.google.com/presentation/d/1g1m34-7qLwxKhFbRzT4MdYQCwrSCIvUej4M1wJtXl8g/edit?usp=sharing)
**insert deliverables here as they go**

**Comment by sanjana-ajit** [comment]
Update: I am going through the sticky notes present on the "BOP Awareness and Usage" MIRO board and the Brigades' Highest Priorities sheet.

**Comment by sanjana-ajit** [comment]
Update: I am creating and sorting the notes on MIRO - Ongoing task.
