### ISSUE TITLE
Update the Transcription Template sheet.

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#203]
### Overview
We want to update the template so that the first row reflects the new format. 

### Resources/Instructions
[The template to be changed](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)

**Comment by Baleja** [comment]
<img width="1454" alt="Screenshot 2021-03-30 at 11 04 45" src="https://user-images.githubusercontent.com/75342357/113035170-ce03e780-9147-11eb-9bef-f8e29608a217.png">

**Comment by Baleja** [comment]
<img width="1507" alt="Screenshot 2021-03-30 at 11 07 51" src="https://user-images.githubusercontent.com/75342357/113035585-381c8c80-9148-11eb-8675-8bd6a0f8ab5f.png">
Wonder woman

**Comment by MarianneAnthonette** [comment]
@thadk I've gone ahead and updated the transcription template header. Hopefully, I didn't break anything so please check the template sheet to confirm that it's good
