### ISSUE TITLE
Create work breakdown schedule 

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#23]
### Overview
Determine the breakdown of activities and schedule to accelerate delivery of research phase (interviews)

### Action Items

- [x] Naomi and Bonnie to meet to determine activities and schedule
- [x] Create template to document breakdown of activities
- [x] Create interview invitation for Brigade participants

### Resources
[UXR Schedule](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs/edit#gid=0)

[Invitation to Participate Email](https://docs.google.com/document/d/1ZjNE674nZXDPd2L7ULg_BEjdaOESwMB9exyBNeWakAM/edit)

[BOP WBS & OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/)

**Comment by naomiec** [comment]
- Testing
   - recruit sample group from Western Brigade Call on Wednesday 8/26
- Determine time frame for BOP interviews to happen
   - start date, duration
- Recruiting
   - text (what the message will be)
   - location  (where we'll post it)
- Onboarding
   - plan
   - zoom links
- Scheduling Interviews
   - get UXRs to sign up for time slots
   - create messaging doc for brigades
      - publish schedule to brigades
      - follow up with brigades that don't select a time
   - create custom URLs for each brigade that responds
- Conduct Interviews
   - fill out spreadsheet to report completed interview

**Comment by MasSamH** [comment]
Thanks Naomi @naomiec and @ExperimentsInHonesty for sending over the work breakdown schedule. To check, I don't have access to the document linked here: [https://docs.google.com/spreadsheets/d/12uNxqK9ZCrXuZzRJF1NSZVqkiSEcqU4YTC8WxHVHI8Q/edit#gid=0]

**Comment by MasSamH** [comment]
@thadk please add the time-zones to: [UXR Schedule - Brigade Timezone, Regional Reference Page](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs/edit#gid=983608097
url)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty @naomiec @thadk Here is the updated[Messaging for Brigade Interview Scheduling](https://docs.google.com/document/d/1ZjNE674nZXDPd2L7ULg_BEjdaOESwMB9exyBNeWakAM/editurl)

**Comment by MasSamH** [comment]
Working version [BOP WBS & OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616)

**Comment by MasSamH** [comment]
Hi @ExperimentsInHonesty @thadk First draft of the spreadsheet to capture BOP Project WBS & OKRs with assigned MOCHA roles. The last component, I've left off those roles, apart from the ones we agreed for Will (NAC). If we have time to review at our meeting later and agree those, plus any other suggestions.
[BOP Project WBS, OKRs, MOCHA](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616)
Speak in a short while. 
Thanks
Sam

**Comment by MasSamH** [comment]
@thadk to add links from the related Github issue into the OKR document here: [OKR document](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty will create a new issue to cover the testing process
