### ISSUE TITLE
Status Update re: Topic Theming and Report

### ISSUE THREAD

**Issue by ag2463** [codeforamerica/brigade-playbook#239]
### Overview
We will use this Issue as a place for Mari to update the BOP team on the status/progress of topic theming and the related report to be created.

### Action Items
Weekly Updates provided by Mari:

- [x] Week of 7/18 
- [x] Week of 7/25
- [x] Week of 8/1
- [x] Week of 8/8
- [x] Week of 8/15
- [x] Week of 8/22
- [ ] Week of 8/29
- [ ] Week of 9/5

### Resources/Instructions
[BOP Report](https://docs.google.com/document/d/1BKGxGzdPL0VNqzTTPa0KTEZtGz61xKHJpi2u0KBc3HI/edit?usp=sharing)
[BOP Report Feedback Form](https://forms.gle/X41gC8t9zfc2yvdB6)
[BOP Data Tables](https://docs.google.com/spreadsheets/d/1AL_-4vOmoNGssNrpucKW-6ylUnWxd0xMQJ3SP8QkVYM/edit#gid=1107698985)
[BOP Analyses](https://docs.google.com/document/d/1sF6Re1nJKzl64OLktzoZj2BJKPnO82E2_-MyEs7YXZ4/edit#)

**Comment by MarianneAnthonette** [comment]
**Week 1 Update Part 1** (more updates at the end of the week but this is a big one)
- Data orgs and transcriptions are **complete**.
- Audited all BOP quantitative data and made two versions of the final overall ratings and the final 'critical' ratings. ([more in-depth view in this sheet](https://docs.google.com/spreadsheets/d/1AL_-4vOmoNGssNrpucKW-6ylUnWxd0xMQJ3SP8QkVYM/edit#gid=1107698985))
 
    - Multi Avg: Multi-person interviews treated as one averaged score (rounded up).
    - Multi Sep: Multi-person interview scores are separated per person (so 77 different data points).
    - Did not include two interviews in the data (one interview was done in the context of GYR/the other is self explanatory)

![Critical Brigade Ratings by Topic (Multi-person interview scores are separated)](https://user-images.githubusercontent.com/20882817/126578339-38a80b1b-7e96-4261-9a45-a6c1adf466a3.png)
![Critical Brigade Ratings by Topic (Multi-person interview scores are averaged + rounded up)](https://user-images.githubusercontent.com/20882817/126578346-91bf07b3-a4c2-4af0-971d-6362e657d86f.png)
![BOP Study Topic Ratings (Multi-person interview scores are separated)](https://user-images.githubusercontent.com/20882817/126578350-cf9b24ff-7938-4559-94d1-72eadfdff536.png)
![BOP Study Topic Ratings (Multi-person interview scores are averaged)](https://user-images.githubusercontent.com/20882817/126578354-d563d905-f174-46a2-b271-64da1720ccbc.png)

**Comment by MarianneAnthonette** [comment]
**Week 2 Update**
- **Rating question analysis**: Fundraising, brand and media strategy, and project strategic plan topics are currently being analyzed and will be complete by Monday 8/2
- **Additional topics question analysis**: Sub-themes were grouped on Miro, sub-theme tags moved into Google sheets for data filtering, analysis of the top 5 groups has started and is in progress.

**Comment by MarianneAnthonette** [comment]
**Week 3 Update**

**Rating question analysis**: DEI goals, building a core team, brigade strategic plan, fundraising, brand and media strategy, project strategic plan, and finally, Code of Conduct have been themed. Clean-up of themes and gathering of quotes will happen next week.

**Additional topics question analysis**: Theming for volunteer recruitment and engagement, project management, collaborating and connecting within the network, brigade leadership, partnerships) has been complete. Clean-up of themes and gathering of quotes will happen next week.

Other things: **Awareness and usage qualitative analysis** has started. Responses to the final thoughts question have been pulled for key quotes usage as well.

**Comment by MarianneAnthonette** [comment]
**Week 4 Update**

- BOP Awareness and Usage analysis is complete
- Themes have been mostly cleaned (need to double-check terms with the CfA glossary Rene Joy has been working on). 
- All quotes for the report have been identified and cleaned up.
- BOP Research Plan doc has been updated (link to it will be added to the report's appendix, including some other docs I'll have to update but that's low priority).
- This weekend, I'll be creating and finalizing the report's charts.

**Comment by MarianneAnthonette** [comment]
**Week 5 Update**

- All quotes, themes, and charts for the report have been finalized. 
- Both of us have been pretty busy during the week (which we already planned for since week 1), so most of the report making will be worked on during the weekend. 
- Completing ￼min. 90% of the report will be the goal by the end of next week (the other 10% are the methods and other research background information).

**Comment by ExperimentsInHonesty** [comment]
This issue is being closed because the report was deliverd.
