### ISSUE TITLE
Review MOCHA & RACI role frameworks to determine applicability

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#25]
### Overview

Volunteers, organizers and org reps need to have a agreed up set of roles, responsibilities and reporting so that all parties will be moving along together towards the finish line!

### Action Items

- [x] Will to send template for MOCHA (please edit this writeup to put the link in the Resources section).
- [x] Review both frameworks to determine applicability 
- [x] Review project roles against frameworks
- [x] Annotate the Work Breakdown schedule with chosen framework details

### Resources

**RACI**

- **RACI Links**
[Steps to creating a RACI matrix](https://www.projectsmart.co.uk/raci-matrix.php )
[RACI blueprint](https://www.cio.com/article/2395825/project-management-how-to-design-a-successful-raci-project-plan.html )

- **RACI definitions**

  - Responsible: People or stakeholders who do the work. They must complete the task or objective or make the decision. Several people can be jointly Responsible.

  - Accountable: Person or stakeholder who is the "owner" of the work. He or she must sign off or approve when the task, objective or decision is complete. This person must make sure that responsibilities are assigned in the matrix for all related activities. Success requires that there is only one person Accountable, which means that "the buck stops there."

  - Consulted: People or stakeholders who need to give input before the work can be done and signed-off on. These people are "in the loop" and active participants.

  - Informed: People or stakeholders who need to be kept "in the picture." They need updates on progress or decisions, but they do not need to be formally consulted, nor do they contribute directly to the task or decision. 

**MOCA** 
[MOCHA definition via The Management Center](https://www.managementcenter.org/resources/assigning-responsibilities/)

- Manager: Assigns responsibility and holds owner accountable. Makes suggestions, asks hard questions, reviews progress, serves as a resource, and intervenes if the work is off-track.

- Owner: Has overall responsibility for the success or failure of the project. Ensures that all the work gets done (directly or with helpers) and that others are involved appropriately. ~~There should only be one owner.~~ There can be multiple owners in some contexts.

- Consulted: Should be asked for input or needs to be bought in to the project.

- Helper(s): Assists with or does some of the work.

- Approver: Signs off on decisions before they’re final. May be the manager, though might also be the executive director, external partner, or board chair.

**Comment by ExperimentsInHonesty** [comment]
Read this article tonight: https://www.linkedin.com/pulse/problem-raci-ray-sheen/

**Comment by MasSamH** [comment]
Hi Bonnie @ExperimentsInHonesty , 

Some really good challenges to the RACI model in those articles. Summary below of alternatives. I've add another option from Bain Consulting (RAPID). 

Speak later, 

Thanks Sam

**RACI Limitations** 
- Remove the complexity and introduce a more effective approach that centers around approval and delivery.
- The RACI matrix assigns a role to each individual, but it does not clarify what they are supposed to do. 
- Who plans the task – the “Accountable” person or the “Responsible” person?
- What is the difference between being Accountable and Responsible?
- Does the “Consulted” person only participate when asked, or are they expected to engage and ensure their perspective is included?
- What about the people who need to be involved in actually doing the work?

**Alternatives to RACI**
More suitable approaches for projects, that support activity based actions, rather than roles. 
DACI – Drivers, Approvers, Contributors, Informed – a variation that focuses on the type of activity that the person does rather than their role.
CLAM – Contributes, Leads, Approves, Monitors – another variation that focuses on the type of activity rather than roles.

**RAD**
Responsible - ensures output or end result
Approve - veto power on a decision and sign off actions
Deliver - provides information, analysis, and other support to responsible person
‘RAD’ framework – a simple way of assigning responsibility for activities, identify who needs to approve the work, and who else needs to be involved to make it happen. 

**RAPID (from Bain Consulting)**
[RAPID](https://www.bain.com/insights/RAPID-tool-to-clarify-decision-accountability) 

![image](https://user-images.githubusercontent.com/69813451/91640959-98681600-ea21-11ea-95be-41ed79bafc1c.png)

**DARCI**
- “D” (Decider) is always the director of the department the project resides in, or the Executive Director herself. 
- The “A” (Accountable) is the most important role. While the D will be giving final approval, the A makes sure the project is keeping to its timeline and connects all the moving parts. 
- There may be several people assigned “R” (Responsible). Rs create the moving pieces that are put together by the A. 
- The “C” (Consulted) are often also multiple people. These people may not even be within the organization. 
- Cs do not generate any work, but the work done by Rs may be shaped by conversations with the Cs. Lastly, “I” (Informed) for us is the rest of the company. We like to keep everyone knowledgeable about the projects happening in all departments, so weekly we all meet for one to two hours to report on the current projects.

**Comment by MasSamH** [comment]
Hi Will, @willpfeffer 

Thank you for providing the background to MOCHA. 

Please let us know where CfA fits into the MOCHA framework as it relates to the scope of work below (initial engagement).

This will help us finalize the project one sheet. 

Look forward to hearing from you. 

Thanks
Sam

Scope of work: to canvass the BOP end-user - the Brigade Organizers - to understand their pains, wants, and needs. Identifying effective processes and practices - including the state of shareability they are in - and analyzing/synthesizing to provide a written report.

This scope of work will be used as part of the larger project to help extend Code for America’s Brigade Organizer’s Playbook (BOP), building on the existing product and improving its value as a communal, high-value resource for sharing best practices in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals, etc.

Outside of scope of initial engagement is rewriting/restructuring/publishing the BOP.

**Comment by ExperimentsInHonesty** [comment]
Have updated the workdown breakdown schedule, will continue
we will add Will to OKR and One sheet consultation and approval when done.
we will provide summary of C, I, A in spreadsheet form.

**Comment by MasSamH** [comment]
Hi Will @willpfeffer 
We have documented the Work Breakdown Schedule, alongside OKRs, and attributed MOCHA roles for CfA. Can you confirm that you okay with these assigned responsibilities?
We have assigned the MOCHA roles based on the discussion with you a few weeks ago. 

[BOP Project WBS & OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/)
Thanks 
Sam
