### ISSUE TITLE
UX Researcher Recruitment Channel Outreach

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#32]
### Overview
We need to identify and post the recruitment message to all relevant channels to ensure successful recruitment drive of UX team.

### Action Items
- [x] Identify potential channels to post recruitment message
- [x] Create spreadsheet of channels
- [x] Draft the message
- [ ] Post recruitment message to pilot number of channels to gauge results
- [ ] Create strategy for how and when to post
- [ ] Execute strategy

### Resources/Instructions
[Messaging Doc](https://docs.google.com/document/d/15qXN1Doqvm31KM-EBwhxcN7lMDCuE7WGYgpSPrKspTE/edit#)

**Comment by thadk** [comment]
Bonnie and Naomi took over these pieces. Mari also posted to Facebook and two UXR Slack's: "Mixed Methods" and "Product Classroom".

**Comment by thadk** [comment]
@ExperimentsInHonesty Curiosity : where did you advertise to find UXRs?
