### ISSUE TITLE
Set up and transfer data to Airtable 

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#34]
### Overview
We need to move data across from Google Docs / Sheets into Airtable platform to help data transferability and extraction.

### Action Items

- [ ] Request access from Will for Airtable. Ask the following questions: 
   - [ ] Can we make some parts private, others 100% public?
   - [ ] What are the limitations of usage?
- [ ] Identify fields of data to move across from Brigade Contract Directory to Airtable
- [ ] Second priority to move across Google Expressions of Interest Form to Airtable TBD

### Resources/Instructions
[Brigade Contact Directory - HfLA Version](https://docs.google.com/spreadsheets/d/12uNxqK9ZCrXuZzRJF1NSZVqkiSEcqU4YTC8WxHVHI8Q/edit?usp=drive_web&ouid=116527607586876940242
)
[UXR Schedule - Brigade Timezone, Regional Reference Page](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs/edit#gid=983608097)
[UXR Schedule](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
@willpfeffer suggested the free tier on a non CfA account.  I agree that should be sufficient for now.  We will set this up under the bop@hackforla.org email address.   Moving to prioritized backlog for now.

**Comment by ExperimentsInHonesty** [comment]
@willpfeffer turns out the free version wont work for us.  Isn't it possible for CfA to setup an empty base for us, and just give us rights in that base?

**Comment by willpfeffer** [comment]
@ExperimentsInHonesty I will check and get back to you as soon as possible

**Comment by MasSamH** [comment]
@willpfeffer Please provide an update on this issue

**Comment by ExperimentsInHonesty** [comment]
Hi @willpfeffer we still need to know if we can use airtable.  For instance we are having an issue where we want to make some data public automatically, but only when it meets certain criteria and we need to keep all the data in one place. Airtable allows us to publish just the appropriate material as its added to the db.

Can you let us know if we can have a dbase for this project?  We only need one user.

**Comment by ExperimentsInHonesty** [comment]
Will posted the following:

Will Pfeffer  8:51 AM
Hi bonnie, I’m not going to make the BOP meeting today (need to focus on Congress), but I realized I hadn’t followed up with you on Airtable. I hadn’t realized this, but the Network team also just uses the free tier of Airtable. I’m not sure whether or not other units at CfA have paid for their own license, but it’s not something we have an org-wide subscription to.

**Comment by thadk** [comment]
We ended up using Google Sheets instead of Airtable b/c we didn't make progress on the above.
