### ISSUE TITLE
Respelling for logo

### ISSUE THREAD

**Issue by thadk** [codeforamerica/brigade-playbook#36]
Need to use source image for "Brigade Organizers Playbook Extension project"

<img width="254" alt="image" src="https://user-images.githubusercontent.com/283343/93924147-58274b00-fce2-11ea-9b59-6bbd2aafcaa9.png">

- [x] Create a revised graphic with appropriate font and spelling, preferably from original version.
- [x] Naomi will update Top of form image

**Comment by ExperimentsInHonesty** [comment]
I remade the logo and updated the [communication guide](https://docs.google.com/presentation/d/1uIRCQXKmOYifAhGOQArK0JMmlksE7U4KvuMN0Be11-0/)

![Screen Shot 2020-09-23 at 12 46 25 PM](https://user-images.githubusercontent.com/37763229/94064336-633fb100-fd9e-11ea-8c3a-d078e3ea9d43.png)

**Comment by MasSamH** [comment]
Run check on entire Google Drive that correct logo displays
