### ISSUE TITLE
One-sheet for project

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#4]
### Overview
Write a one-sheet for the BOP project including milestones for the next X months.

### Action Items
- [x] SAM
   - [x]  Review VRMS and Civic Opportunity one-sheet
   - [x]  Produce First Draft of [One-Sheet](https://docs.google.com/document/d/1GkvbJ9byBWBpZklYE6YL5nqa-KbIRz32PnMCeroV_1g/edit?ts=5f3ff6e6)
 - [x]  Sam to convert One Sheet into new BOP brand style 
   - [x]  Prepare questions for review with Bonnie
- [x] WILL
   - [x] fill in missing gaps on the history - invite to Tues, Thursday
- [x] SAM
   - [x] Release dependency #5 
   - [x] Populate 'As-is' state, source background information from Will Pfeffer 

### Resources/Instructions
[All Project One Sheets](https://github.com/hackforla/product-managment/issues/3)
[VRMS Doc](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit)
[Civic Opportunity Project One-Sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)

**Comment by ExperimentsInHonesty** [comment]
@MasSamH i have updated the one sheet with the branding and edited the content that Tom provided into a narrative.  The dependency on #5 is released.

**Comment by MasSamH** [comment]
@ExperimentsInHonesty You beat me to it. It looks ace. 
Shall I move #5 to 'Work in Progress' or keep in the Prioritized Backlog?

**Comment by MasSamH** [comment]
@willpfeffer Hi Will, hope your week is going well. 
We are ready for the CfA review and sign-off on the BOP Extension Project [One Sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/edit)
Any questions, do let Bonnie or myself know.
Thanks
Sam

**Comment by willpfeffer** [comment]
@MasSamH This looks great! Consider the Network Team signed off on the one sheet.
