### ISSUE TITLE
Design Training and related materials

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#41]
### Overview
We need a plan and materials for running the UXR training.

### Action Items
- [x] make new deck
  - [x] include slides for 
   - [x] Agenda (3 min)
   - [x] Overview of CfA and the brigades (2 min)
   - [x] Overview of the project (3 min)
      - [x] History of the BOP
      - [x] Current Mission
   - [x] Instructions (5-10 min)
      - [x] Read
      - [ ]Q & A into fun retro
      - [x] combining and reviewing fun retro questions
   - [x] Pairing off to try delivering the survey to each other, switch off to the e(30 min)
      - ( add notes with q#s to fun retro as you go, use email@email.com, select 1 for the first scale question, and 0 for the second, read each one, and choose 1 for all the rest, and only have two processes and practices).  
   - [x] Break (7 min)
   - [x] Fun Retro Q & A for questions (15 min)
   - [x] Next Steps
      - [x] Get a UXR number if you feel ready to conduct interview (5 min)
      - [x] Signup for next training if you do not feel ready
   - [x] Add their first two weeks of availability (15 min)
- [x] email to invite UXRs that have indicated interest via form
- [x] UXR instructions
- [x] UXR schedule
- [x] Fun Retro
- [x] write follow-up email with links to:
   - [x]  UXR instructions
   - [x] BOP UXR schedule spreadsheet in case they need to change their availability

### Resources/Instructions
[UXR Instructions](https://docs.google.com/document/d/1cQumMP3mBUR595ZUkOgxoiLPkLL4WmgRWcAP_e3cWoQ/)
[BOP UXR schedule](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs)
[BOP Slide template](https://docs.google.com/presentation/d/1YKxew7FwCN3UiC58rZNoAAtVnLGd__626o3CwngEHw0/)
[BOP Invite for training](https://docs.google.com/document/d/1ZT03kjXwHO9hk_m-1zOnylaRqT38aCZnXbaaQFw0fOY/edit)
[UXR Interview training deck](https://docs.google.com/presentation/d/1oDGQvBvippkJg4D_s4ZPKJHXTyoKDLya8VNZv58mDyY)
Fun Retros
- [UXR Instructions Q&A](https://funretro.io/publicboard/goqvAZJ4bDeStqnYW14FABRyoQs1/a125b819-7ad6-46a6-8b07-36af72a7daf0)
- [UXR Interview Practice Q&A](https://funretro.io/publicboard/goqvAZJ4bDeStqnYW14FABRyoQs1/8b1ccfdd-afe6-495f-90e2-f57687bcb836)

**Comment by MasSamH** [comment]
Add a slide for the CfA Qualitative Research Guide to the deck

**Comment by MasSamH** [comment]
Going to add into the training materials the details about the Transcription.

**Comment by ExperimentsInHonesty** [comment]
@thadk put instructions for audio upload into slide 17 https://docs.google.com/presentation/d/1oDGQvBvippkJg4D_s4ZPKJHXTyoKDLya8VNZv58mDyY/edit#slide=id.ga76703771d_0_9

**Comment by ExperimentsInHonesty** [comment]
@MarianneAnthonette move content from one to the other (fun retro), delete all the stuff that got answered by instructions and slide deck updates,

**Comment by ExperimentsInHonesty** [comment]
@MarianneAnthonette the fun retro looks good.

**Comment by ExperimentsInHonesty** [comment]
transcription training is being addressed in issue https://github.com/codeforamerica/brigade-playbook/issues/48
