### ISSUE TITLE
Setup Fun Retro

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#42]
### Overview
We need to have fun retro boards setup for feedback on the UX training so that we can reduce the time we spend on Q&A while still getting qualitative information that we can use afterwards.

### Action Items
- [x] Signup for funretro under the bop@hackforla.org email
   - [x] Setup two boards for the workshop for questions from the workshop

### Resources/Instructions
[Fun Retro signup](https://funretro.io/register)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty Hi Bonnie, I've set up the Fun Retro account (ignore the BOP Gmail phone authentication request that came through earlier). 
On the Fun Retro dashboard, see what you think of the custom template [Capture Questions URX Training Fun Retro](https://funretro.io/publicboard/goqvAZJ4bDeStqnYW14FABRyoQs1/a125b819-7ad6-46a6-8b07-36af72a7daf0) 
If this is okay, I'll create another board for session 2. Thanks Sam

Password for Fun Retro account is Bopiterate2020

**Comment by ExperimentsInHonesty** [comment]
Please setup a fun retro board for the training and add each of us to the board

**Comment by MasSamH** [comment]
@ExperimentsInHonesty login details (including password) for Fun Retro are now safely stored in the BOP 1password for HackLA account. [Issue 42](https://github.com/codeforamerica/brigade-playbook/issues/42)

To add team members to Fun Retro requires premium account, at a cost of $26 per month. Let me know how you want to proceed. Thanks Sam

**Comment by MarianneAnthonette** [comment]
@MasSamH Can you make another board for session 1? There are supposed to be two boards for each training session:
(Naming scheme below)
UXR Instructions Review Q&A
UXR Interview Practice Q&A

**Comment by MasSamH** [comment]
@MarianneAnthonette Just saw your note re two boards for each session. See that there's a limit - max of 3 boards - for the free account. Maybe after the first session, we can delete the boards from the first, and that will free up two boards for the second session? [Issue 43](https://github.com/codeforamerica/brigade-playbook/issues/42)

**Comment by ExperimentsInHonesty** [comment]
Fun Retros
- [UXR Instructions Q&A](https://funretro.io/publicboard/goqvAZJ4bDeStqnYW14FABRyoQs1/a125b819-7ad6-46a6-8b07-36af72a7daf0)
- [UXR Interview Practice Q&A](https://funretro.io/publicboard/goqvAZJ4bDeStqnYW14FABRyoQs1/8b1ccfdd-afe6-495f-90e2-f57687bcb836)
