### ISSUE TITLE
Deck for Brigade Congress

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#43]
### Overview
We lighting deck for BC to communicate value of project to potential brigades and uxrs

### Action Items
Brigade Congress Presentation

- [x] deck
   - [x] Overview and outcomes (summarize below)
   - [x] Next steps: Get Involved
      -  [x] Brigade
      -  [x] UXR
       - [x] Join the team (to help with Analyzing & synthesizing data) - see schedule (https://github.com/codeforamerica/brigade-playbook/projects/1#card-43964552) on repo and join us via slack channel (cfa slack channel name organizers playbook
   
-[ ] links
   - repo
   - one sheet
   - join the team
   - interest form for chat
   - uxr interest form

### Resources/Instructions

WBS after the interviews
- Analyzing & synthesizing data (informed)
  - Trend analysis
     - highest priorities
        - by ALL
        - by Size of Brigade
        - length of leadership
        - by Region
      - Assets
        - by Topic Areas
        - by Readiness 
        - by Type
        - by numbers of times mentioned (same asset mentioned by multiple brigades)
      - BOP Awareness & Usage Analysis
        - knowledge of 
        - number of people using 
        - frequency of use
        - helpfulness
    - Create summary report
    - Affinity Mapping Process to determine themes and insights (refer to the Qualitative Research Practice Guide)
- Write recommendations (consulted/helper)
- Presentation of analysis to CfA and NAC
  - Create slide deck to present summary and highlights
     - Now that we have this round of insights, who else do we need to talk to?
     - What areas can we dig into further?
     - What additional questions do we have?
  - Schedule Presentation to CFA and NAC
  - Deliver Presentation 
  - Discuss Next Steps & Recommendations (Open call to NAC members to be consulted/helper)

**Comment by thadk** [comment]
Slide deck template: https://docs.google.com/presentation/d/1Om0wvexH2p9O2HIGKnTLIzUCCDHhEWfMLg0AWIzpWBQ/edit

**Comment by thadk** [comment]
Deck: https://docs.google.com/presentation/d/114PaYxISNpAs01NuomLJAz2kRMhpnnbYd4dMUo1_fJI/edit#slide=id.g9e2fd1b862_1_112

**Comment by ExperimentsInHonesty** [comment]
all that remains is script for each section and to time it out.
