### ISSUE TITLE
Procedure for handling new Calendly reservations

### ISSUE THREAD

**Issue by thadk** [codeforamerica/brigade-playbook#44]
### Overview
When a new Calendly reservation comes in from another brigade leader:

- we should edit the UXR spreadsheet with it
- ask the two UXRs to sort out who is the primary and secondary according to if a transcriber is needed.
- add the primary UXR (or both) to the calendly invitation on the BOP@hackforla.org calendar.

### Dependencies
- Mari's draft to the interviewers will be like: "When to expect it, what to do in the mean time. We will be reaching out to you when your interview is scheduled." She would like to explain the interview time period in that email.

### Action Items
- [ ] Check with Bonnie 
- [ ] Clarify the interview timeline with Bonnie.

**Comment by MasSamH** [comment]
Marianne is continuously operationalizing this request.
