### ISSUE TITLE
How to handle interview requests for non-Brigade leads 

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#45]
### Overview
We need to establish a process to handle interview requests from non-Brigade leads 

### Action Items

- [x] Review non-Brigade lead response 
- [x] Determine what message to send 
  - [x] New potential Brigade organizer 
  - [x] A Brigade member not in leadership
- [ ] Send message

### Resources/Instructions
- New potential Brigade organizer 
Thank your interest in the BOP Project and a Brigade Leader interview. At this time we are only interviewing current Brigade leads. Here's the link to our Project Overview. Can you tell us what your interest is for being interviewed? We would love to help you with any next steps. 

- A Brigade member not in leadership
Thank your interest in the BOP Project and a Brigade Leader interview. At this time we are only interviewing current Brigade leads and specific Brigade members they identify as having effective processes and practices that we need to document. Here's the link to our Project Overview. If there is popular demand by Brigade leads we will create a self-service version of the interview for Brigades to poll their members.

**Comment by ExperimentsInHonesty** [comment]
Here is the email I sent to the one person who mentioned that they were not yet a brigade lead after I realized they were currently one of our remote volunteers at HfLA.

Hi ----, 

I saw that you filled out the BOP Project and a Brigade Leader interview interest form at Congress. At this time we are only interviewing current Brigade leads. Here's the link to our Project Overview.

I didn't realize you were interested in starting a new brigade!  I think you are on the right track, volunteering at HackforLA if the approach is to model what you see working and take time to define what your own brigade might look like.  Successful project management is a big part of that.

I would be happy to talk more about this in the future.

Best regards, 

Bonnie
