### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#46]
### Overview
We have added a lot of new resources and work product to the project that we want to be visible and navigable. 

### Action Items
- [ ] Figure out which items from the project board are not yet on the readme
   - [ ] Add items to the readme as appropriate
   
### Resources/Instructions
[current readme](https://github.com/codeforamerica/brigade-playbook/blob/master/README.md)

**Comment by ExperimentsInHonesty** [comment]
# Brigade Organizer's Playbook Extension Project

### Overview
The Brigade Organizer’s Playbook (BOP) Extension Project is an initiative of the Code for America National Advisory Council (NAC). 

The BOP Extension Project seeks to build on the existing product and improve its value as a communal, high-value resource for sharing best practices in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals, etc.

🌐 This project is 100% open source, transparent and community led
- Our work flow is available online at our [GitHub Project Broad](https://github.com/codeforamerica/brigade-playbook/projects/1) 
- As we do our research we will be adding the P&P assets to this [spreadsheet](https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit?usp=sharing)

**Project context**
Each of the 80+ Code for America Brigades generates valuable learnings in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals. What worked and how to replicate some of these are documented in the current Brigade Organizer’s Playbook.

Both the NAC and CfA independently identified the need to have replicable templates of processes and practices as part of their strategic priorities for 2020, to help scale the impact of Brigades' work to transform Civic life through technology.

**The initial Scope of Work (SOW)** 
Exploratory interviews with Brigade Organizers - to discover what best practices and processes exist, as well as report on what future needs would improve the ongoing collection and sharing of learnings across the network.

For more information the initial SOW and its milestones, refer to: [Brigade Organizer's Playbook One Sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/)

---

### How to Contribute
   -  Brigade Leaders, UX Researches, and general project people - We need you!  [Please read our BOP Extension Project Getting Involved Guide](https://docs.google.com/document/d/1A2Tyqu4oqQevJa3vlrqeOrGT-jANs6CIbgyOpKKdcds/edit?usp=sharing)

### Communication channels
- GitHub: [Project Management Board](https://github.com/codeforamerica/brigade-playbook/projects/1) & [UXR Team Management Board](https://github.com/codeforamerica/brigade-playbook/projects/2)
- CfA Slack [#bop-share-effective-practice](https://cfa.slack.com/archives/G0196272BBN)
- Email [BOP@hackforla.org](mailto:BOP@hackforla.org) 

### Project Leadership
   - Agile Mentor & CfA National Advisory Council BOP project Co-Lead
      - Bonnie Wolfe [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UGREE50MT)
   - CfA National Advisory Council BOP project Co-Lead
      - Thad K. [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UAU40G31A)
   - CfA Brigade Network team representative
      - Will Pfeffer [email](wpfeffer@codeforamerica.org) or [CfA Slack](https://codeforamerica.slack.com/team/U014MEJV6KT)
   - Product Manager 
        - Sam H. [CfA Slack](https://codeforamerica.slack.com/team/U019C4LERSM)
   - UX Research Team Lead      
        - Marianne Miranda [CfA Slack](https://codeforamerica.slack.com/team/U01ASEG8HK5)
   - Special Projects Coordinator
      - Naomi Chao [CfA Slack](https://codeforamerica.slack.com/team/U018DSK3231)







_Volunteer management is being provided by the Hack for LA - Civic Tech Structure team._

**Comment by MasSamH** [comment]
@MarianneAnthonette Hi README is updated with you role. Any changes, let me know, thanks Sam

**Comment by ExperimentsInHonesty** [comment]
@MasSamH add past contrib section and move naomi to it, add Raquel and John to the Current Leadership
slack member id
https://codeforamerica.slack.com/team/[insert memberID]

**Comment by MarianneAnthonette** [comment]
@MasSamH Edit Readme with the following roles:
- Raquel Nishijima: Communication Designer & UX Researcher
- Jon Kropko: Data Scientist

**Comment by MasSamH** [comment]
@raquelnish @jkropko both of you are added to the Project Readme. Any changes, let me know. 
Naomi moved to 'Past Contributors' section. 
Thanks Sam
@ExperimentsInHonesty

**Comment by MarianneAnthonette** [comment]
@MasSamH You forgot to add "Designer" after "Communication" for Raquel's Role

**Comment by ExperimentsInHonesty** [comment]
Updated Raquel's id to be the one on the cfa slack.

**Comment by MasSamH** [comment]
@MarianneAnthonette @ExperimentsInHonesty Updated readme with Research Analysis team. Thanks Sam
