### ISSUE TITLE
Create BOP Readme for Repo

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#5]
### Overview
Communicate the BOP Project goal via a readme file so it is easy for new people joining to understand the project, and get up to speed.

### Dependancies
Creation of one sheet #4  - released

### Action Items
- [x] Review with Bonnie the readme file and identify what information is needed and applicable (put notes in comments below)

   - [x] Review the project one sheet and identify which of that information belongs in the readme.
   - [x] Review Civic Opportunity & 100 automations Repository Readme and follow as as a best practice template 
  - [x] Review final draft with Bonnie.

**Things to include:**
- [x] Overview paragraph
- [x] Project Context 
   - [x] wording 
   - [x] link to the one sheet
- [x] Leadership
   - Agile Mentor & CfA National Advisory Council BOP project Co-Lead
      - Bonnie Wolfe [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UGREE50MT)
      - CfA National Advisory Council BOP project Co-Lead
    - Thad K. [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UAU40G31A)
      - Product Manager 
        - Sam H. [CfA Slack](https://codeforamerica.slack.com/team/U019C4LERSM)
   - Special Projects Coordinator
      - Naomi Chao [CfA Slack](https://codeforamerica.slack.com/team/U018DSK3231)
- [x] Technology used
    - [x] GitHub: [Project Management Board](https://github.com/codeforamerica/brigade-playbook/projects/1) & [UXR Team Management Board](https://github.com/codeforamerica/brigade-playbook/projects/2)
    - [x] CfA Slack [#bop-share-effective-practice](https://cfa.slack.com/archives/G0196272BBN)
    - [x] Email [BOP@hackforla.org](mailto:BOP@hackforla.org) 
- [x] How to Contribute
   -  Brigade Leaders, UX Researches, and general project people - We need you!  [Please read our BOP Extension Project Getting Involved Guide](https://docs.google.com/document/d/1A2Tyqu4oqQevJa3vlrqeOrGT-jANs6CIbgyOpKKdcds/edit?usp=sharing)

### Resources/Instructions
[Readme template](https://github.com/hackforla/.github/blob/master/README.md)
[BOP One Sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/edit)
[Civic Opportunity Repository Readme](https://github.com/hackforla/civic-opportunity/blob/master/README.md)
[100 Automations Readme](http://100automations.org)
[BOP Extension Project Getting Involved](https://docs.google.com/document/d/1A2Tyqu4oqQevJa3vlrqeOrGT-jANs6CIbgyOpKKdcds/edit?usp=sharing) Guide

**Comment by ExperimentsInHonesty** [comment]
Hi @MasSamH while I was making the project card, I realized I better do the leadership links for the readme (since its fairly complicated and only a one time task), and then I just ended up adding some other stuff too (see top of this issue).  What remains is for you to write the project context and overview.

**Comment by MasSamH** [comment]
Hi Bonnie, @ExperimentsInHonesty 

How about the below as 'overview' and 'context' for the Readme?
 
Wasn't sure how much to add on the 'context' since the other examples simply link directly to their respective One Sheet. I can add more or cut down, whatever you think.

Once I get you edits back, I'll drop all the text in a googledoc or is there another template for the submission?

Thanks
Sam

---Start---

The Brigade Organizer’s Playbook (BOP) Extension Project is an initiative of the Code for America National Advisory Council (NAC) and is delivered in partnership with Hack for LA. 

The initial Scope of Work seeks - via exploratory interviews with Brigade Organizers - to discover what best practices and processes exist, as well as report on what future needs would improve the ongoing collection and sharing of learnings across the network. 

Project context

Each of the 80+ Code for America Brigades generates valuable learnings in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals. What worked and how to replicate some of these are documented in the current [Brigade Organizer’s Playbook](https://docs.google.com/document/d/1G_v53fGyHqdZNmXkDxqhqkzT7q2TBZ9Xmh9JkWtFQ8Y/edit#heading=h.v3vvoe3g4dep).

For more information on the project, refer to: [Brigade Organizer's Playbook One Sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/edit)

---End---

**Comment by MasSamH** [comment]
Both the NAC and CfA independently identified the need to have replicable templates of processes and practices as part of their strategic priority to help scale the impact of Brigades' work to transform Civic life through technology.

**Comment by ExperimentsInHonesty** [comment]
### Overview
The Brigade Organizer’s Playbook (BOP) Extension Project is an initiative of the Code for America National Advisory Council (NAC). 

The BOP Extension Project seeks to build on the existing product and improve its value as a communal, high-value resource for sharing best practices in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals, etc.

**Project context**
Each of the 80+ Code for America Brigades generates valuable learnings in topic areas such as fundraising, recruiting members, running remote brigades, project management, setting and achieving DEI goals. What worked and how to replicate some of these are documented in the current Brigade Organizer’s Playbook.

Both the NAC and CfA independently identified the need to have replicable templates of processes and practices as part of their strategic priorities for 2020, to help scale the impact of Brigades' work to transform Civic life through technology.

**The initial Scope of Work (SOW)** 
Exploratory interviews with Brigade Organizers - to discover what best practices and processes exist, as well as report on what future needs would improve the ongoing collection and sharing of learnings across the network.

For more information the initial SOW and its milestones, refer to: [Brigade Organizer's Playbook One Sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/)

### Project Leadership
   - Agile Mentor & CfA National Advisory Council BOP project Co-Lead
      - Bonnie Wolfe [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UGREE50MT)
   - CfA National Advisory Council BOP project Co-Lead
      - Thad K. [email](mailto:bonnie@hackforla.org) or [CfA Slack](https://codeforamerica.slack.com/team/UAU40G31A)
   - CfA Brigade Network team representative
      - Will Pfeffer [email](wpfeffer@codeforamerica.org) or [CfA Slack](https://codeforamerica.slack.com/team/U014MEJV6KT)
   - Product Manager 
        - Sam H. [CfA Slack](https://codeforamerica.slack.com/team/U019C4LERSM)
   - Special Projects Coordinator
      - Naomi Chao [CfA Slack](https://codeforamerica.slack.com/team/U018DSK3231)

### Technology used
- GitHub: [Project Management Board](https://github.com/codeforamerica/brigade-playbook/projects/1) & [UXR Team Management Board](https://github.com/codeforamerica/brigade-playbook/projects/2)
- CfA Slack [#bop-share-effective-practice](https://cfa.slack.com/archives/G0196272BBN)
- Email [BOP@hackforla.org](mailto:BOP@hackforla.org) 

### How to Contribute
   -  Brigade Leaders, UX Researches, and general project people - We need you!  [Please read our BOP Extension Project Getting Involved Guide](https://docs.google.com/document/d/1A2Tyqu4oqQevJa3vlrqeOrGT-jANs6CIbgyOpKKdcds/edit?usp=sharing)


_Volunteer management is being provided by the Hack for LA - Civic Tech Structure team._

**Comment by MasSamH** [comment]
Could use a formatting fix on the 'Open source 100%' section. Follow up action.

**Comment by MasSamH** [comment]
Hi Bonnie, Thad, Naomi,

Sorry for the late notice. I’m not able to make the call today.

We are making a dash for the UK to visit parents. Thursday, I’ll be back to
join our calls.

One update to share, the OKR/work breakdown schedule with MOCHA roles is
ready for your review.

I’d add the issue and link, but am blocked from github under the channel!

Hope your weekends went well.

Cheers Sam
