### ISSUE TITLE
Determine where we track and report UXR activity

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#52]
### Overview
We need to determine when interviews and assets are completed and have this information readily available. 

### Action Items

- [x] Determine where we want to capture and keep track of interview status 
- [x] Determine when assets are uploaded e.g. transcription

### Resources/Instructions
- Where UXRs indicate their availability [UXR Schedule](https://docs.google.com/spreadsheets/d/1vSqxDaq8RoNudW3gsqWHLAS6PQCbRAvH7OVuMDYbqBs/edit#gid=0)
- Where you can see Completed/Canceled/Scheduled interview details [Interview Responses + Tracking](https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit#gid=1930219941)
- Where we get the names of the brigades we have left to invite to interviews [Brigade Contact Info sheet - HfLA version (annotated)](https://docs.google.com/spreadsheets/d/12uNxqK9ZCrXuZzRJF1NSZVqkiSEcqU4YTC8WxHVHI8Q/edit#gid=0)
- Place where we publicize the assets gathered from interviews [P&P Assets public](https://docs.google.com/spreadsheets/u/1/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit?usp=drive_web&ouid=115931314350257714190)
- Place where we evaluate assets gathered from interviews for publication readyness [P&P Assets internal](https://docs.google.com/spreadsheets/d/1ZyeIDeHnzwjnkfYuhzeUZQo5tYXpbdnF-HKqN8cZy_A/edit#gid=0)

**Comment by MasSamH** [comment]
@MarianneAnthonette @ExperimentsInHonesty @raquelnish @thadk Currently the status of completed UXR activity is kept in the Bridge Contacts Directory, as well as columns in the UXR schedule re translations. Can we agree a 'one location' for these on the next call.

**Comment by MarianneAnthonette** [comment]
Made a copy of the tracking spreadsheet to the interview responses spreadsheet per Thad's suggestion, however, I'm unsure where the interview responses spreadsheet is actually located. Will delete the sheet in the contact directory (hfla) once this is resolved.

@thadk ^^^ Where is it actually located/is it not actually in a folder?

**Comment by Baleja** [comment]
@MarianneAnthonette Please move the interview responses spreadsheet to the shared drive. https://drive.google.com/drive/u/1/folders/0AHm1jtnPQgtkUk9PVA

**Comment by Baleja** [comment]
@Baleja After access is granted audit the difference.

**Comment by celeste-hub** [comment]
@raquelnish  to moved the interview responses and tracking to BOP, now @Baleja you should have access now.

**Comment by Baleja** [comment]
@Baleja Create new reference card with appropriate sheets for new UXR people.
