### ISSUE TITLE
Validate and define interview response segments

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#55]
### Overview

We need to validate and define the interview response segments (e.g. size, region, length of brigade leadership) to ensure research data is properly categorized for the analysis phase. 

### Action Items
- [ ] Review and correct information for each interview
   - [x] **Size**: Create a column on the tracking sheet to place the quantified Brigade size
   - [x] **Region**: Cross-reference CfA Brigade data and correct the region on the tracking sheet
   - [x] **Length of brigade leadership**: Create a column on the tracking sheet to place the quantified length of leadership
- [x] Define the criteria for each sub-segment so we can filter the data.

### Resources/Instructions
[Interview Responses + Tracking Sheet](https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit?pli=1#gid=1930219941)
[Brigades & Reps by Metropolitan Statistical Area](https://docs.google.com/spreadsheets/d/1KzYXMggfgFraUsl-ltJUp_VhjGDEjDoV98CvpcoJd14/edit?usp=sharing)

**Comment by thadk** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/283343/102727462-bec50080-42f3-11eb-8800-87152505e2f9.png">
Quantile sizes of brigades spoken to so far as of Dec 20th.

**Comment by thadk** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/283343/102728387-a35cf400-42f9-11eb-87ca-1b89a440e94a.png">

**Comment by Baleja** [comment]
From Mari:
This was an old issue that was updated
About making sure that our pivots (e.g. size, region, length of brigade leadership) from the responses are corrected and cleaned up. Also about defining the criteria of the sub-segments (what is considered a small, medium, large brigade, etc.)
Located in Prioritized Backlog in the UXR board (location in project management board could be changed).
It’s an ongoing issue as new interviews come in (a huge bulk of responses were validated by Thad). Thad would be the one to be assigned when new bulk of interviews comes in.

**Comment by Baleja** [comment]
To be added to instructions in #122 @raquelnish to add quantifiable size, region, length of brigade leadership. 
1year =1
6 months = 0.5
4 months = 0.5

**Comment by ExperimentsInHonesty** [comment]
I would like to understand what part of the process this is and if its in the icebox what is its dependency

**Comment by Baleja** [comment]
Chart positioning and labeling has been changed to represent relationships better.
