### ISSUE TITLE
Review transcriptions from interviews

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#56]
### Overview
We need to review transcriptions and identify sentiment, and key phrases to ensure the correct data feeds into the analysis phase.

### Action Items

- [ ] Review transcriptions to get an understanding of the interviews
- [ ] C+V and separate text (if multiple things are brought up for one question)
- [ ] Highlight important phrases

**Comment by MarianneAnthonette** [comment]
@MasSamH Delete this issue; the tasks in this issue were moved to #57
