### ISSUE TITLE
Set up Methodology for reviewing and analyzing transcriptions

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#57]
### Overview
We need to create a framework to organize each of the transcription sheets to trace responses from interviewees and analyze responses against key priorities. 

### Action Items
- [x] Trial various methodologies for analyzation workflow
   - [x] Create individual spreadsheets for each section/research question that needs to be analyzed (make a new folder called ‘Research Analysis’)
   - [x] Find a way to tag the responses so that they can be traced back to interviewee/pivots (size, region, length of leadership)
- [x] Create template for assigning each interview to be analyzed. 
- [x] Create instructions for: 
    - [x] Transcription Verification
    - [x] Data organization   
    - [x] Coding
    - [x] Tagging
     
### Resources/Instructions

[Transcription Verification Instructions](https://docs.google.com/document/d/1kTrslqYY0whUjCMxbcV7Ft1nzCr_UTPWXfhomNgOvEw/edit)
[Data Organization Instructions](https://docs.google.com/document/d/1vJqDQ8Th8kSgisSSiMzDpRHTIWI3ILCX4eOTgMwRdoY/edit)
[Coding Instructions](https://docs.google.com/document/u/0/d/10am6Ki0gJKzITt2kcjMsR233oC_9WJneKnFimFc8Mao/edit)
[Tagging Instructions](https://docs.google.com/document/d/1soNmLMyVspkgz2MMD5DuF_WVBBmnFLFgCPNZDjxjDWI/edit#)

**Comment by thadk** [comment]
Mari and Raquel have done a first pass of two interviews to determine codes in Brigades’ Highest Priorities sheet above.

WEDNESDAY Meeting: There will be instructions in a sheet for the analyzers at the upcoming Wednesday meeting. We'll determine when all the analysis will be done.

 - Do we need to create a coding dictionary? 
- What are things we can do to prepare bigger conversation for each research question that we have? 
   -  Some of the additional topics are mainly qualitative. 
   - The ranking section includes both Quant and Qual. Who is going to work with who–we can task action items that we can anticipate at that meeting,

**Comment by MarianneAnthonette** [comment]
Data organization and initial review task has been assigned [here](https://docs.google.com/spreadsheets/d/1vI_UfdHd8PkFX2HTIc3QTtsO-o0-jbJt5hvyyIKrCH0/edit#gid=0). This task will be completed for the 13 completed transcriptions by the next research analysis meeting (still has to be scheduled; [LettuceMeet link](https://lettucemeet.com/l/xV2Vx)).

**Question**: What is considered a small, mid, large Brigade? Is there anything else we need to do to validate this information?

**Goals for next meeting**:
- Discuss patterns and interesting quotes (and see initial patterns based on pivots)
- Discuss, assign, and begin next steps (memoing, initial codes, other methods, transcriptions, etc.)

**Comment by thadk** [comment]
https://docs.google.com/spreadsheets/d/1KzYXMggfgFraUsl-ltJUp_VhjGDEjDoV98CvpcoJd14/edit?usp=sharing

**Comment by MasSamH** [comment]
Update coming tomorrow, 09.12.

**Comment by MarianneAnthonette** [comment]
- Data from 8 interviews have been moved into the consolidated analysis spreadsheets (@myrandi @reemux will continue the data organization for the ones they were assigned to last week)
- Mari will send out a message once more interviews are ready to be transcribed + organized

**Comment by MasSamH** [comment]
- [ ] Raquel to copy and paste from tracking sheet and to let Marianne know to message 
- [ ] Only ones not available (Michael Chow) and the one from Puerto Rico

**Comment by Baleja** [comment]
@MasSamH Who is this comment assigned to? https://github.com/codeforamerica/brigade-playbook/issues/57#issuecomment-742675785
Can we get an update on here?

**Comment by celeste-hub** [comment]
@jkropko to run the script on interviews. Michael Chow, Froilan, Pamela, Eric from ABQ
@thadk and @MarianneAnthonette look at the best way to automate data organisation

**Comment by MasSamH** [comment]
- Discussed best way to automate the data and issue created #120
- Marianne awaiting on Thad for data organization element @thadk 
- Marianne working on the data automation instructions (tagging & coding, data organization, and transcription verification.

**Comment by MarianneAnthonette** [comment]
- Progress: Transcription verification and coding instructions have been worked on.
- Blockers: Catching up with transcriptions + interview prep. Also need to create filter views for the analysis sheet so the coding instructions can be completed.
- Availability: Will be more available after Friday
- Estimated date of completion: Tuesday

**Comment by MarianneAnthonette** [comment]
Progress: Tagging and coding instructions nearly complete.
Blockers: Catching up with transcriptions + was busy w/ interview prep. Waiting for Thad's data organization part.
Availability: Will be more available after Friday
Estimated date of completion: Tagging and coding instructions - EOD. Data organization - End of week

**Comment by Baleja** [comment]
Continuing on issue #120

**Comment by MarianneAnthonette** [comment]
Progress: Tagging and coding instructions complete. Working on data organization instructions.
Blockers: None
Availability: Free this week now.
Estimated date of completion: Friday

**Comment by MarianneAnthonette** [comment]
Progress: Data organization instructions are complete
Blockers: None
Availability: --
Estimated date of completion: It's done.
