### ISSUE TITLE
Get research analysis volunteers (all levels) up to speed

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#58]
### Overview
We need to ensure rapid assimilation of research analysis volunteers into the project to scale capacity and apply consistent approach to information processing and data analysis.

### Action Items

- [x] Schedule group discussion call
- [x] Add volunteers to roster 
- [x] Grant access to Github (Thad, Bonnie)
- [x] Add Research Analysis team to Readme (Sam)
- [x] Separate project board (UXR Team Management) 
- [x] Establish weekly meeting cadence with the UXR Team 
- [x] Give access to ‘Research Analysis’ folder (and possibly ‘Transcription Storage’)
- [x] Send project documents that give more context about the study
- [x] Assign research analysis activities

### Resources/Instructions

[LettuceMeet Link](https://lettucemeet.com/l/GgerB)
[Research Analysis Plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit?pli=1)

**Comment by MasSamH** [comment]
Marianne scheduling with research analysts volunteers for Wednesday 2nd, 11am, PST.

**Comment by MasSamH** [comment]
Marianne has sent the agenda. Meeting to go ahead tomorrow. 11am PST.

**Comment by MarianneAnthonette** [comment]
Research analysis volunteers have access to the Research Analysis and Transcription storage folder. Still need Github access and add to roster and ReadMe (and check Otter.ai access). Their e-mail and Github handle can be found in the [UXR Number/Name tab](https://docs.google.com/spreadsheets/d/1vI_UfdHd8PkFX2HTIc3QTtsO-o0-jbJt5hvyyIKrCH0/edit#gid=911932312).

Weekly meeting still has to be scheduled ([LettuceMeet link](https://lettucemeet.com/l/xV2Vx)).

**Comment by MarianneAnthonette** [comment]
The research analysis team will meet weekly on **Wednesdays, 11am-12pm PST**.

@MasSamH Greenlight to add the additional research analysis volunteers onto the Readme (their info is on the Team Roster).

**Comment by MasSamH** [comment]
@MarianneAnthonette Updated readme with details of the research analysis volunteers, thanks Sam

**Comment by MasSamH** [comment]
@MasSamH an update to Readme with Tan and add Serena, Product Manager.

**Comment by MasSamH** [comment]
Issue complete
