### ISSUE TITLE
Research Plan Creation & Updating

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#60]
### Overview
We need to build out a comprehensive research analysis plan to ensure the research insights are synthesized into the final report recommendations. 

### Action Items

- [x] Draft initial plan 
- [x] Review with Team Members 
- [x] Review with wider Research Analysis Team 
- [x] Amendments made to plan  
- [x] Review with Team Members

### Resources/Instructions
[Research Analysis Plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit#heading=h.4j218gtyxygu)

**Comment by MasSamH** [comment]
@MarianneAnthonette has edited on the document. On 2nd Dec. further review of the document. Meeting agenda sent.

**Comment by MarianneAnthonette** [comment]
Next research analysis plan will be updated after the next research analysis meeting (not scheduled yet).

**Comment by MasSamH** [comment]
Status as per previous update. 
Marianne is sending Serena invite to the meeting.  
Add to the left 'Start here' of the Github board.
Agenda sent already. [Agenda](https://docs.google.com/document/d/1Qz6sG3xD0yaVmMsVaqFiG57H94oexMtDSrEmh3agwQQ/edit?usp=sharing
)

**Comment by MarianneAnthonette** [comment]
The research analysis plan has been updated. Further and more detailed amendments will be made in their respective issues [#65, #66].

**Comment by celeste-hub** [comment]
@raquelnish to add a brief summary of the competitive analysis to the research analysis plan.

**Comment by raquelnish** [comment]
@celeste-hub the brief summary was added to the [Research analysis plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit#)

**Comment by Baleja** [comment]
@MarianneAnthonette See raquels additions & Let us know the next steps

**Comment by Baleja** [comment]
@MarianneAnthonette  Add link to the Interview Priority template to the Research Analysis plan and how this process works.

**Comment by Baleja** [comment]
Bonnie to review document and assess by Sanjana whether it codifies the research analysis substantially enough to be used by other projects.

**Comment by MarianneAnthonette** [comment]
- Progress: None
- Blockers: Catching up with transcriptions + interview prep
- Availability: Will be more available after Friday
- Estimated date of completion: Sunday

**Comment by MarianneAnthonette** [comment]
- Progress: Added some stuff about template issue but will add more today.
- Blockers: None
- Availability: 6 hours (will be busy starting Tuesday)
- Estimated date of completion: Saturday EOD

**Comment by MarianneAnthonette** [comment]
- Progress: Finished adding the info about the template issue. I need to rework the timeline section.
- Blockers: None
- Availability: This week, I can only allow time for this project during the meetings on Tuesday, Wednesday. I'll be free after Thursday. I won't be able to make the Thursday meeting.
- Estimated date of completion: 1/22

**Comment by MarianneAnthonette** [comment]
Moved to IceBox for review. Other issues are more important for me to focus on at the moment (research analysis-related).

**Comment by MarianneAnthonette** [comment]
Research questions have been updated. Will update the rest of the sections prior to Saturday and by then, will send a message on Slack to researchers + Jon to review prior to Tuesday and Wednesday.
Estimated date of completion: Friday

**Comment by MarianneAnthonette** [comment]
Document has been updated + Slack messages sent
