### ISSUE TITLE
Procedure for Using Template for Each Transcription

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#62]
### Overview
We need a clean copy of the method and process for using the transcription template. The template enables transcribers to import responses from the google form directly into a Google sheet where the words and notes can be annotated, completing the transcription process. 

### Action Items

- [x] Clean up the procedures for use

**Procedure for use:**
![Screen Shot 2020-12-17 at 17 24 04](https://user-images.githubusercontent.com/71442493/102521373-c5057380-408c-11eb-8a90-313ead62d7de.png)

_Please do not share it as-is: It has full access to our interviewees' results.
Note: You must edit only in the first sheet/tab because they are in the specific interview order._
- [ ] Pick which row of the main results you want by entering the corresponding number in cell B1 on the second sheet/'Pick Target Row'.
- [ ] On the first sheet/'Edit screen', copy the entire sheet.
- [ ] Right-click on the sheet name and select Copy to -> New spreadsheet to make a copy of the template sheet onto a new spreadsheet. 
- [ ] In the new spreadsheet, delete the current values (this way you don’t get the formulas).
- [ ] Paste values only into the new spreadsheet. 
- [ ] Freeze the first header row by selecting View->Freeze->1 row.
- [ ] Rename the new spreadsheet using the audio naming scheme (UXR#_brigadename_interviewyear-interviewmonth-interviewday_FirstName-LastName)
   - [ ] **Example 1**: 007_hackforla_2020-09-28_Bonnie-Wolfe 
   - [ ] **Example 2**: 003_codeforcharlottesville_2020-10-22_Jonathan-Kropko
- [ ] Change the sheet name from 'Edit screen [copy/paste values to new spreadsheet]' to 'Transcription'.
- [ ] Make Otter.ai public with the full link and add the full link to the spreadsheet.
- [ ] Move the spreadsheet into the 'Transcription Storage' folder.
- [ ] Add the spreadsheet link to the 'BOP Interview Responses and Tracking' sheet.
- [ ] Share the new spreadsheet with the transcriber along with other necessary files.
- [ ] Once the interview is completely transcribed (as indicated by the transcription status in the tracking sheet is 'Complete'), turn-off the public access to the Otter.ai link.
- [ ] Tell Thad when the transcription spreadsheet has been completed so Thad renames the Otter.ai.

### Resources/Instructions

[Transcription Sheet Template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)
[BOP Interview Responses and Tracking](https://docs.google.com/spreadsheets/u/1/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit#gid=1930219941)
[Otter.ai Group](https://otter.ai/group/360630)

**Comment by MarianneAnthonette** [comment]
Updated the procedure for use above.

**Comment by MasSamH** [comment]
@thadk will review the procedure.

**Comment by Baleja** [comment]
@MasSamH Why did we move this to internal reference material?

**Comment by celeste-hub** [comment]
@MasSamH @ExperimentsInHonesty @celeste-hub to create a wiki page with the procedures and add the wiki page to reference column.

**Comment by Baleja** [comment]
We will be adding this info to the wiki through issue #125
