### ISSUE TITLE
Notify VRMS of Team Meeting Times

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#7]
### Overview
VRMS (Volunteer Relationship Management System) needs to know details of weekly team meetings

### Dependency

- [x] When project card is on website #9 

### Action Items

Defined Times: 

Weekend - Saturday 8pm (CET) 11am (PDT) 2pm (EDT) 1pm (CDT) 12noon (MT)
Weekday - 6pm (CET) 9am (PDT) 12pm (EDT) 11am (CDT) 10am (MT)

- [x] Meeting occurrence 1 x weekend (Saturday) 
- [x] Meeting occurrence 2 x weekday (Tuesday, Thursday)
- [x] Notify VRMS of weekly team meetings once project card issue completed

**Comment by clockwerkz** [comment]
I can add these meetings into vrms - how long are the meetings?

**Comment by ExperimentsInHonesty** [comment]
@clockwerkz the meetings are 1.5 hours each

**Comment by clockwerkz** [comment]
I went ahead and added them in.

**Comment by ExperimentsInHonesty** [comment]
I checked and its not yet done https://github.com/hackforla/VRMS/issues/308#issuecomment-714815352

**Comment by ExperimentsInHonesty** [comment]
Resolved
