### ISSUE TITLE
Common transcription mistakes for multipurpose use.

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#71]
### Overview
Reviewing and analysing transcript picking out funny quotes which were mispronounced and what Otter ai picked up.

### Action Items
- [x] Create spreadsheet to track permissions on quotes
- [x] Populate spreadsheet with quotes
- [x] Add who said the quote (interviewee or interviewer)
- [x] Reach out to interviewee or interviewer as appropriate to confirm we can use.
- [x] Add funny quotes to a deck.

### Resources/Instructions
[Spreadsheet](https://docs.google.com/spreadsheets/d/1GeTjLSUFP-reDpntQdlvlPTFFfoHaL3hyVTkOWf-mtQ/edit#gid=0)

**Comment by jkropko** [comment]
We replaced "i'm in a remote cricket" with "running a remote brigade" in 014_codeforbaltimore_2020-11-10_Jason-Anton.txt

We replaced "tuesday manager per day" with "tools to manage your brigade" in 013_codeforboulder_2020-11-03_Jacob-Venable.txt

We replaced "any topics that's not a, that's not in the list" with "are there any topics not in this list" in 013_codeforboulder_2020-11-03_Jacob-Venable.txt

We replaced "baudin corking" with "building a core team" in 013_codeforboulder_2020-11-03_Jacob-Venable.txt

We replaced "processes that you find effective" with "do you have any effective processes" in 013_opencolumbus-ohio_2020-11-14_Vijay-Yadav_Mihir-Amin.txt

We replaced "someone violates, how to deal with the why violation" with "how to deal with code of conduct violations" in 013_codefororlando_2020-10-31_Krystina-Ramos.txt

We replaced "okay, and next one is fundraising" with "drafting a strategic plan for a project okay, and next one is fundraising" in 013_codefororlando_2020-10-31_Krystina-Ramos.txt

 We replaced "work.\n\ndevelopment" with "workforce development" in 027_openoakland_2020-11-16_Jess-Sand.txt

**Comment by jkropko** [comment]
We replaced "drafting strategic plan for every day" with "drafting a strategic plan for your brigade" in 027_codeforpuertorico_2020-11-27_Froilan-Irizarry-Rivera.txt

**Comment by MasSamH** [comment]
- Marianne has sent out an invite for the meeting and is awaiting responses from UXRs.

**Comment by Baleja** [comment]
Bonnie will make a spreadsheet to provide a place to identify permission level quote.
