### ISSUE TITLE
Check MOU status for Brigades to trigger further outreach

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#72]
### Overview
We need to check whether Brigades have signed a MOU and whether they are active - if they are - then we can approach for interview.

### Action Items

- [ ] @thadk to approach Cici to confirm that Brigades have signed a MOU so we know relative active status (and can reach out)

**Comment by ExperimentsInHonesty** [comment]
@cfischerbenitez Can you provide an updated list of brigades that have signed the mou?  We need it to know who to stop trying to contact (i.e., they have not signed an mou, so we don't need to interview them for the BOP work).

**Comment by cfischerbenitez** [comment]
Hi Bonnie, you can find the updated list [here](https://docs.google.com/spreadsheets/d/1_auMf0YI8YO7xSn_zOgg9lxOUwqhFPmQWmWNoTbtPbs/edit?usp=sharing). We still have a couple of Brigades who still need to sign, this doc will be updated once they sign.

**Comment by Baleja** [comment]
Thad has updated the sheet with new and active brigades.
