### ISSUE TITLE
Create communication guide

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#8]
### Overview
Increase engagement with BOP Playbook by developing a style guide for the overall navigation and visual appearance.

### Action Items

- [x]  Define a color guide - using the cfa website style guide for colors
- [x]  Define a typography system - using the cfa website style guide for colors
- [ ]  Create key components
- [ ]  Send templates to Will for review (informed)

### Resources/Instructions

[BOP Communications Guide](https://docs.google.com/presentation/d/1uIRCQXKmOYifAhGOQArK0JMmlksE7U4KvuMN0Be11-0/edit#slide=id.g8078b36bb8_0_371)
[codeforamerica style guide](https://style.codeforamerica.org/)

**Comment by ExperimentsInHonesty** [comment]
update:
1. Progress: 
- I started on the communications guide. 
- I got the doc template done
- The slide deck and sheet still need to be done.
2. Blocks: none
3. Availability: pretty good today
4. ETA: End of day Friday 8/27

**Comment by ExperimentsInHonesty** [comment]
I forgot how many hours goes into one of these.  I won't be done with this for another few days.  The templates for the google doc, spreadsheet and slides have been created.  Next up is the google and airtable form headers and other settings.  I will work with Naomi on those.

**Comment by ExperimentsInHonesty** [comment]
@naomiec  the reason why the image did not work as a header is because its not 800x400 so its warping it as it displays it so first you have to resize and crop the photo get it to 800 x 400 and then you can add the book cover to it.  Let me know if you need help getting this done.

**Comment by ExperimentsInHonesty** [comment]
@naomiec I put the logo for this into issue #36

**Comment by MasSamH** [comment]
@thadk add updated image to google drive and add the link to the folder in this issue. Create a folder for all 'image assets' (in google drive).

**Comment by ExperimentsInHonesty** [comment]
I added a google form template.  I am also adding a link to the relevant links to a card https://github.com/codeforamerica/brigade-playbook/projects/1#card-47092804. If we decide to use AirTable, add the airtable template.
